### ISSUE TITLE
Crash with Better Nether

### ISSUE THREAD

**Issue by paulevsGitch** [apace100/origins-fabric#1]
Good day, here is an [issue ](https://github.com/paulevsGitch/BetterNether/issues/129). Looks like Origins adds not final tag(s).  They are not initiated at game startup and due to mod order causes crash

**Comment by Worgrick** [comment]
i can second this one really exicted about your mod

**Comment by apace100** [comment]
Thanks for reporting and thanks for looking into it paulevs, will be fixed in the next version which I'm uploading right now to CurseForge. :)
