### ISSUE TITLE
Github home Wiki page is broken

### ISSUE THREAD

**Issue by GamyGamer** [apace100/origins-fabric#100]
As in title, I wanted to check wiki for stuff and homepage is broken
Screenshot:

![image](https://user-images.githubusercontent.com/49346764/108073055-e9b7a080-7067-11eb-8b53-aafc695de67a.png)

**Comment by apace100** [comment]
Yeah, I saw this as well. I hadn't changed anything with the wiki though, and after a while this was fixed again for me.
If you are still experiencing this, try clearing your cache of the GitHub domain.

**Comment by KatolickiFriedChicken** [comment]
GamyGamer, has the wiki fixed for you, and if so about how long did it take? I have cleared the cache and waited for a little over an hour.

**Comment by godlikeanimal** [comment]
Having the same issue here. No fixes, and it's been happening for about an hour or two.

**Comment by colmak** [comment]
clearing cache of the GitHub domain fixed it for me
