### ISSUE TITLE
Suggestion: More Orbs, configurable orbs, and lockable to individual layers.

### ISSUE THREAD

**Issue by pleasejustletmehaveafuckingusername** [apace100/origins-fabric#101]
now that you have added a secondary ability key bind, the next step would be to add more "blank" orbs, that do nothing, unless told what to do.
some cool fields might be:
"origins:lock_to_layer", optional, list of layers (this would allow the orb to only show the specified layers when it is used)

"origins:orb_name", optional, string, default="blank_orb" this will be the translation key for the item name when you hover your mouse over it in-game.

"origins:consumable", boolean, default= true, when set to false, the item will not disappear when used.

I had this idea shortly after having the idea of a "spell slot" layer.

**Comment by apace100** [comment]
Orbs are now customizable to only work on specific layers or even choose specific origins, via their NBT data. This has been added in version 1.1.0
