### ISSUE TITLE
LAN world problem, connection lost

### ISSUE THREAD

**Issue by Feyhre** [apace100/origins-fabric#102]
Hi!
Me and my bro where starting a coop LAN world with Origin. Host perfectly fine (like in solo survival), but 2nd player can't connect to the world. Got a "Connection Lost" message directly after "Loading Terrain" message shows up. 
Could be great if you can investigate this !

**Comment by apace100** [comment]
This seems like the version mismatch issue. You need to make sure you both have the same version of Origins installed. I recently updated the mod, so if one of you installed later, even though you both got the "most recent" version, one of you might have gotten 0.4.7 while the other downloaded 0.4.6.
