### ISSUE TITLE
Suggestion: Add secondary keybind for second layer origins.

### ISSUE THREAD

**Issue by HimitsuYami** [apace100/origins-fabric#103]
I was testing out the second layer origins example datapack and tried to combine Elytran with Shulk to make up for the armor limitations of Elytran. However since both origins have active powers (Shulk inventory and Elytran boost) you can't use one without attempting to use the other. This results in opening your Shulk inventory every time you want to use the Elytran boost and attempting to boost any time you want to open your Shulk inventory. My suggestion is to be able to separate the keybinds either by adding one for secondary powers or by splitting every power to have a distinct keybind.

**Comment by maffe03** [comment]
I think there already is a secondary keybind, it's just that when using the default origins they all bind to the first one. You'd probably need to change that through the datapack.

**Comment by maffe03** [comment]
Yep, here it is in the [wiki](https://github.com/apace100/origins-fabric/wiki/Key)

**Comment by SarahScript** [comment]
> Yep, here it is in the [wiki](https://github.com/apace100/origins-fabric/wiki/Key)

Can I ask how you would code that? I'm trying to work that out right now.

**Comment by apace100** [comment]
The second layer data pack is just an example of how layers work, it's not supposed to be actually used. You are free to modify it though to fit your needs, it is possible to change the keybinds (you would have to create alternate versions of the origins, which use alternate version of the active powers which have their keybinding changed to the secondary power key).
