### ISSUE TITLE
Problem with Modify player spawn, not working 

### ISSUE THREAD

**Issue by Rwstix** [apace100/origins-fabric#108]
I've been trying for like 3 hours to understand why it isn't working and it still not working....
so here is the the end spawn text and the origins one... hope that someone can help me. I've tried without end_spawn and it's working perfectly fine. So the problem is clearly this...

{
  "type": "origins:modify_player_spawn",
  "dimension": "minecraft:the_end",
  "structure": "minecraft:end_city"
  },
 "name": "End Inhabitant",
 "description": "you spawn in the end." 
}

{
	"powers": [
		"origins:translucent",
		"origins:water_vulnerability",
		"inanis:air_swimming",
		"inanis:damage_from_no_sky",
		"inanis:no_exhaustion",
		"inanis:end_spawn"
	],
	"icon": "minecraft:end_crystal",
	"order": 10,
	"impact": 3,
	"name": "Inanis",
	"description": "Born in the overworld, the Inanis has been cursed by the Master of the end this way they will always wander in his dimension."
}

**Comment by apace100** [comment]
The ID of the End City is `endcity`, not `end_city`. I'm sorry, I really should have implemented better error checking and reporting here. The wiki confused me here at first as well, I actually encountered the same problem as you. I figured it out by checking the `/locate` command in-game.

**Comment by Rwstix** [comment]
Thanks !
