### ISSUE TITLE
[Suggestion] Allow Origins to have upgrade hooks

### ISSUE THREAD

**Issue by TheMisteryMan** [apace100/origins-fabric#11]
The mod is a very interesting idea, with quite a few interesting ideas, but I've come to a realization.
Quite a few of the origins special perks become not so useful once you've gotten later into the game.

For example, Elytrian become practically useless once you can get an elytra, as sure you can wear a chestplate as elytrian, but you're limited to up to Chainmail tier.

My solution? Levelling/upgrades, for example, you could either do an XP system by using the perks of the Origin, or unlock new perks, or disable old perks/cons once the player gets an advancment, or crafts, or obtains an item.

For example, once an Elytrian picks up an Elytra:
- Allow using armour up to iron tier
- Lower the launch ability cooldown
- Make the launch ability launch the player up higher

**Comment by apace100** [comment]
Now possible in v0.3.0 and above, origins can be upgraded to other origins when an advancement is reached.

See [the wiki](https://github.com/apace100/origins-fabric/wiki/Defining-an-origin-in-JSON) for more information.
