### ISSUE TITLE
Once I launch Minecraft from the launcher, Minecraft just never loads. 

### ISSUE THREAD

**Issue by Timeless121** [apace100/origins-fabric#111]
I notice that the launcher is still in the background processes though. The launcher disappears from the taskbar and nothing ever happens afterward.

**Comment by Kymor5** [comment]
I have the same problem.

**Comment by Kryptos13713** [comment]
mine crashes

**Comment by minedog220** [comment]
same here

**Comment by apace100** [comment]
This sounds like a Fabric installation problem and unrelated to Origins. Make sure that you have enough RAM allocated to run modded Minecraft. For more help, please look on other sources online, for example the Fabric Discord.
