### ISSUE TITLE
I can't pick origin.

### ISSUE THREAD

**Issue by Firepaw-2000** [apace100/origins-fabric#112]
When I joined a server with this mod it never had a pop up with the pick your origin and also when I hit O it said I had no origin

**Comment by chris0711x** [comment]
my friend is having the same problem

**Comment by apace100** [comment]
If the Origin selection menu isn't showing up, Origins isn't installed correctly. Either on the client or on the server.

Check whether you get the menu on a singleplayer world. If you do, it's not installed correctly on the server, if you don't it's not installed on the client.
