### ISSUE TITLE
When I try to open Minecraft it just opens the fabric loader and says "could not find required mod: origins requires {fabric @ [*]"

### ISSUE THREAD

**Issue by Brodey-jpg** [apace100/origins-fabric#113]
it also says "creating Empty clause?"

**Comment by Golder06** [comment]
Can you send a screenshot of the error? It's probably just a problem with your Fabric Version or that you don't have the Fabric API installed though

**Comment by bet417** [comment]
@Golder06 I got the same thing that @Brodey-jpg here is the photo:
![2021-02-19 (2)](https://user-images.githubusercontent.com/79328912/108538979-65565f00-72ad-11eb-9d5f-983181f24ea9.png)

**Comment by Golder06** [comment]
Yeah you need to download the Fabric API @bet417 [this is the link](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
