### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Rwstix** [apace100/origins-fabric#118]
I wanna give the merling permanent night vision underwater, is there any way to do it without making a new origins ?

**Comment by maffe03** [comment]
You can change how origins works through datapacks! 
Check out the [wiki](https://github.com/apace100/origins-fabric/wiki) and [example packs](https://github.com/apace100/origins-example-packs)

**Comment by apace100** [comment]
If you join the Discord server, there is exactly this feature as a datapack posted in the datapacks channel! (If you go there, search for "Merling's water vision" and you'll find the pack).
