### ISSUE TITLE
ok so i downloaded fabric and launched with fabric but the mod is still unavailable 

### ISSUE THREAD

**Issue by Brodey-jpg** [apace100/origins-fabric#124]
it just loads normal minecraft, do i have to drag the mod into the fabric folder?

**Comment by Brodey-jpg** [comment]
NVM i fixed it

**Comment by beeman69** [comment]
> NVM i fixed it
how i have the same problem

**Comment by xiaqn** [comment]
i have the same problem, any help?

**Comment by xiaqn** [comment]
for clarification i have the problem of, when i launch it it says that the mod is a fabric mod and cannot be loaded

**Comment by apace100** [comment]
Look online for tutorials on installing Fabric mods (or even specifically for installing Origins) or join the Discord if you need help with this.
