### ISSUE TITLE
Inchling is now extremely small...

### ISSUE THREAD

**Issue by MatchaKitsune** [apace100/origins-fabric#127]
My friend chose inchling as his origin and was originally normal inchling sized, but now he is extremely small, smaller than a single pixel on a minecraft block. We've tried switching his origin but even with the new powers his extremely small hitbox and appearance stays...

Is there any fix or is this supposed to happen?
![image](https://user-images.githubusercontent.com/79497044/108802558-7cb37780-754d-11eb-9704-b176dab11046.png)

**Comment by apace100** [comment]
This is not supposed to happen, it's a bug which will be fixed with the next Origins update.

**Comment by apace100** [comment]
Fixed since Origins 0.5.0

**Comment by Michiel40** [comment]
Here is another picture from another perspective

![Screenshot_156](https://user-images.githubusercontent.com/80398965/110634980-e4eb9580-81aa-11eb-9980-d247ae1abf0b.png)
