### ISSUE TITLE
spider climb not working

### ISSUE THREAD

**Issue by masonbooh** [apace100/origins-fabric#131]
I don't know why but in my survival world my arachnid just forgets how to climb for long periods of time 

I don't have any other mods except the addons

**Comment by AzWasTaken** [comment]
It happens too in my Aternos server and singleplayer world.

**Comment by masonbooh** [comment]
any knowledge of how to fix

**Comment by apace100** [comment]
The climbing is toggleable, meaning you can turn it on and off by pressing G. It might be that you pressed G accidentally and this turned it off without you knowing, then you can just press G to turn it on again.

**Comment by masonbooh** [comment]
thank you comrade
