### ISSUE TITLE
Is There A Way To Edit The Phantom Burning Through Glass? 

### ISSUE THREAD

**Issue by WhyIsCyrusTaken** [apace100/origins-fabric#132]
I want to turn this off because I want to build my base out of glass and because of the sunlight it passes through so I burn can I turn this off somehow?

**Comment by apace100** [comment]
Yes, this is possible to do with a data pack, by overriding the `burn_in_daylight` power of the Phantom and adding a condition which checks for there not being glass above them as well.

However the issue tracker here is not the right place for data pack help (its main use is for bug reports). Please [visit the wiki](https://origins.readthedocs.io/) for more information on Origins data packs, or [join the Discord](https://discord.gg/4mTMHu3) if you need more immediate help with this.
