### ISSUE TITLE
Merling Depth Strider debuff

### ISSUE THREAD

**Issue by C0DEHADES** [apace100/origins-fabric#133]
Using depth strider with a merling doesn't stack with the swimming speed it already has but instead acts with the speed of depth strider being basically useless as it's faster having no boots with it.

**Comment by C0DEHADES** [comment]
Wanted to give an add on, I noticed fins don't work properly with dolphin's grace. As when you don't have depth strider you swim faster only if yo have dolphin's grace, but the swimming speed doesn't increase with the fins ability alone without depth strider.

**Comment by apace100** [comment]
Depth Strider works now with Merling's swim speed (since version 0.7.0)
