### ISSUE TITLE
Merling fix

### ISSUE THREAD

**Issue by C0DEHADES** [apace100/origins-fabric#134]
Merling should be able to use cauldron or water bottles to refill air in nether as there is no other way that seems viable.

**Comment by apace100** [comment]
All the ways a non-Merling can breathe longer underwater, Merlings can use to extend their breath on land. Use a respiration enchantment and a turtle helmet, alongside drinking water bottles, to make your first trips to the nether. Once you have water breathing potions, you're basically all set. :)

**Comment by C0DEHADES** [comment]
then maybe buff air gained by bottles? I tested it and 2 is bit to little how about 4? when I actually gain the breathing potions it'll be useless as I won't need them anymore when I gain blaze roads.
