### ISSUE TITLE
No way of changing

### ISSUE THREAD

**Issue by AzWasTaken** [apace100/origins-fabric#135]
Maybe it could be a good idea to, with the craft of a very expensive new item, be able to change your origin or class. Something that it's for the end game, my friend didn't knew it's basically worthless to be an aracnid and a rogue at the same time because they are incompatible.

**Comment by liadx66** [comment]
u can do /origin set origins:origin origns:<origin name> and im pretty sure it can work for all of the addons too

**Comment by apace100** [comment]
There is an Orb of Origin item which allows changing the origin, though it's unobtainable in survival. You can add a recipe or add it to a loot table via a datapack.

**Comment by AzWasTaken** [comment]
> u can do /origin set origins:origin origns: and im pretty sure it can work for all of the addons too

actually, the thing is getting it via survival, for example my friends couldn't do it if they ain't admin at the server.

**Comment by AzWasTaken** [comment]
> There is an Orb of Origin item which allows changing the origin, though it's unobtainable in survival. You can add a recipe or add it to a loot table via a datapack.

The problem is I don't know any way of modify or create a data pack so it's possible :')

**Comment by jasikpark** [comment]
> u can do /origin set origins:origin origns: and im pretty sure it can work for all of the addons too

I was not able to find this in the documentation: I was trying to do `/origin set origins:avian` for the longest time D:
