### ISSUE TITLE
Not working with lithium

### ISSUE THREAD

**Issue by FireMeg** [apace100/origins-fabric#139]
I tried loading into Minecraft a created new a world and I chose to be a phantom. For some reason, I couldn't go through walls. I finally found what the problem was, for some reason, I can't go through walls wen using the lithium mod made by jellysquid_
pls fix this 

thank you for your time
FireMeg

**Comment by FireMeg** [comment]
Title correction: Phantom origin not working with lithium

**Comment by apace100** [comment]
Update your Lithium version. :)
