### ISSUE TITLE
Is this mod ever going to be for forge as well?

### ISSUE THREAD

**Issue by Sn0wNymph** [apace100/origins-fabric#14]

**Comment by apace100** [comment]
If you look closely on the CurseForge page, there is an old Forge version available (the one for 1.15.2).

I'm not going to work on it anymore, as the versions are quite different from each other (I coded the Fabric version from scratch) and also contain different features. Anyone who wants to can pick up the source code of this version and port it, or update the Forge source code to a newer version if desired, is welcome to do so. I've said this before in the comments on the CurseForge page.

Reasons for why I'm not working on Forge anymore:
1) maintaining 2 versions of a mod which work fundamentally different is a lot of work (essentially maintaining 2 mods)
2) Fabric allows for much more creative freedom in what I want to realize and how
3) I perceive the development community of Fabric as much nicer, friendlier and more open
