### ISSUE TITLE
game crashes after opening 

### ISSUE THREAD

**Issue by Elydias** [apace100/origins-fabric#142]
I don't know what happened but every time Minecraft loads it crashes and says origins is the cause which doesn't make sense because I was able to play it before  :(

[crash-2021-02-24_09.07.48-client.txt](https://github.com/apace100/origins-fabric/files/6034464/crash-2021-02-24_09.07.48-client.txt)

**Comment by Elydias** [comment]
I FOUND THE PROBLEM! :D

**Comment by Dinodude6011** [comment]
how
