### ISSUE TITLE
Cleric Can’t see Enchantments 

### ISSUE THREAD

**Issue by MasterBlast773** [apace100/origins-fabric#147]
When you pick cleric, and look at the enchantments you are supposed to get, you get something completely different, and it can vary. This is due to the better enchants cleric is supposed to have but is rather useless when you don’t actually know what enchants you’re getting.

**Comment by apace100** [comment]
Closing this because it concerns Origins: Classes, not the base mod. See the issue here: https://github.com/apace100/origins-classes/issues/20
