### ISSUE TITLE
Phantom burns in daylight when it's raining and you're sprinting

### ISSUE THREAD

**Issue by J3LL4** [apace100/origins-fabric#150]
On version 0.4.7, on a multiplayer server.

**Comment by apace100** [comment]
Sorry, I couldn't reproduce this issue with:
* Fabric API 0.31.0
* Origins 0.4.7
* Minecraft 1.16.5

I followed these steps:
* Started a dedicated server
* Connected to it and chose Phantom in the selection menu
* Used `/weather rain` to produce rain
* Ran around, exposed to the sky, sprinting and not sprinting, unphantomized and phantomized

At no time was I burning during the rain.
