### ISSUE TITLE
Elytrian bug makes it unplayable

### ISSUE THREAD

**Issue by astrobudder** [apace100/origins-fabric#154]
I'm hosting a bisect 1.16.5 server for me & my friends & anyone with the Elytrian origin just can't glide. The elytra item works but anyone with the origin just appears to begin to glide for a fraction of a second then immediately return to the normal standing position & just fall. Thus, the origin is useless until I can fix this.
If anyone has any clue how I could fix this that would be very helpful & much obliged.

**Comment by apace100** [comment]
Are you sure Origins is installed correctly on the server and the client?
Just to be sure - could you update to the most recent Origins version (0.5.1)?

If you did all this and the bug still persists, please send me a list of all installed mods as well as a server log if possible.

**Comment by astrobudder** [comment]
will do

**Comment by astrobudder** [comment]
That didn't help.
The releavent mods are:
caelus
Customizable eytra
Origins
Extra Origins
Origins Classes
Mob Origins
Phkui

**Comment by astrobudder** [comment]
alright, I'm just gonna remove them all & try adding them one by one till it works,
will let you know when I find the problem mod
(I removed all but origins & it worked so it is a mod thing)

**Comment by astrobudder** [comment]
OKAY!
I've found the mod
It appears that Oh The Biomes You'll Go is causing it not to work for some reason

**Comment by astrobudder** [comment]
Is there a way I can fix this cause I'd like to have both going

**Comment by astrobudder** [comment]
I have determined the problem mod to be Adorn

**Comment by astrobudder** [comment]
ALRIGHT NEVER MIND AGAIN!
I'm not sure what's going on but I'll remove some mods, it'll work, then I'll add everything but those mods again & it don't
I'm not so sure it's a mods issue anymore

**Comment by Mouchtache** [comment]
i had the same problem on my side for me it was trinkets (so artifact) because origin adds your elytra in a virtual chestplate but trinket make that you need to put your elytra in a cape slot

**Comment by Mouchtache** [comment]
and caelus make it bug too

**Comment by apace100** [comment]
Closed, see #191 (and by extension #195)

**Comment by RageMC** [comment]
What was the solution to this?
