### ISSUE TITLE
Shader power type doesn't change based on conditions or changing origins.

### ISSUE THREAD

**Issue by lochnessdragon** [apace100/origins-fabric#158]
If you have a custom power with shader as the type on a custom origin, when you switch origins, the shader isn't removed and the effect still applies. The same goes for if the shader is conditioned based.

Code: 
shader_power.json:
```
{
  "type": "origins:shader",
  "shader": "minecraft:shaders/post/blur.json",
  "condition": {
  	"type": "origins:exposed_to_sky"
  }
}
```

test_origin.json:
```
{
	"impact": 4,
	"order": 1,
	"icon": "minecraft:iron_pickaxe",
	"powers": [ 
		"<modid>:sun_blinded"
	]
}
```

Expected:
- When the player is in sunlight, the "blur" effect should be applied.

Actual:
- The "blur" effect is permanently applied, regardless of switching classes or going into the dark. That is, until you perform a resource reload.

What works:
- If you switch to the origin with the shader power, the shader is applied.

**Comment by apace100** [comment]
Fixed in version 0.6.0.
