### ISSUE TITLE
Spider Climbing Ability Disappeared

### ISSUE THREAD

**Issue by Darkmagicswh** [apace100/origins-fabric#164]
So I chose the spider race as my origin and I love it a lot, but after the third day on a new server with friends in mining and notice my climbing ability has vanished. I still have my 7 hearts, have to eat meat, and webbing stuff but no climbing. I disconnected and reconnected twice, restarted my PC, and even turned off auto jump just in case. All my others mods work too and I had no issue the previous day when I added them on.

**Comment by apace100** [comment]
The climbing ability is toggleable with the primary power key, by default
bound to G. You probably pressed it by accident.

**Comment by apace100** [comment]
If you could confirm that this was the problem, and not an actual bug, I'd appreciate it because then I could close this issue without the stinging doubt that I might have ignored a bug. :D

**Comment by Darkmagicswh** [comment]
Yes, sorry that was the solution to my problem thank you!
