### ISSUE TITLE
Crash report on 1.16.5 Minecraft on MacBook Air

### ISSUE THREAD

**Issue by Squidnugget28** [apace100/origins-fabric#169]
My Minecraft
 keeps crashing on fabric as soon as I installed the origins mod and I didn't have any mods in it until the origin mod I even have all its dependences in the fabric folder too

**Comment by apace100** [comment]
Have you tried following any online (video) tutorials for installing mods? I'm pretty sure there are also specific ones related to installing mods on a Mac.

If you need any more help, please visit the Discord and ask there: https://discord.gg/4mTMHu3
