### ISSUE TITLE
How to use the tag field in Fire Projectile?

### ISSUE THREAD

**Issue by Pegandus** [apace100/origins-fabric#177]
basically, i'm trying to make it so that i can throw a potion using the Fire Projectile power type, and i'm having issues on how to make it a lingering poison potion because i don't know how to convert the NBT data to the tag field.
 any kind of help would be greatly appreciated.

**Comment by apace100** [comment]
I suggest using an online tool, such as a /give command generator, to figure out the NBT. In the "tag" field of the power, you then enter everything from give command that follows after the item id, including the brackets `"tag": "{...}"`
However, you need to make sure that if there are any quotation marks `"` within the tag, those need to be escaped, by putting a backslash `\` in front of each of them.
