### ISSUE TITLE
Crashed with Carpet Mod

### ISSUE THREAD

**Issue by linzexin022** [apace100/origins-fabric#18]
Hi there, I found that your mod is in conflict with Carpet Mod, which is probably caused by reach entity attributes. Carpet is a very good mod to check the running status of the server and modify the features. I wonder if you could make origin compatible with it?

**Comment by linzexin022** [comment]
Here's the game log:
[latest.log](https://github.com/apace100/origins-fabric/files/5005582/latest.log)

**Comment by apace100** [comment]
Hey, this is a compatibility issue of the library I'm using for modifying the Enderian's reach and Carpet, as you found out. Unfortunately there is currently not much I can do about this, but I posted a crash log and a link to this issue on the library's GitHub page, hoping that the author can resolve the conflict.

**Comment by Nathan22211** [comment]
Genoben fixed this on his end
