### ISSUE TITLE
Am i being dumb or can i just not have the mod enabled and improve my server in creative?

### ISSUE THREAD

**Issue by PickledKatsu** [apace100/origins-fabric#182]
I'm mkaing an smp with my friends using this mod and i got it all working, but i needed to add a couple things in creative. After being satisfied with that, my origin just didnt work, i picked elytrian and yeah. nothing happened, I tried giving myself an orb of origin but it just disappeared from my inventory whilst switching to survival, and /give didnt work either, it just said it didnt exist. It's probably me being dumb, if it is, any help?

**Comment by apace100** [comment]
Seems like Origins isn't installed correctly on your server. If it was
before, maybe you accidentally removed it or started your server wrong
after shutting it down (e.g. just starting the vanilla jar instead of the
Fabric server launch)?

**Comment by PickledKatsu** [comment]
it might have been that i started using a craftbukkit server jar as well, so yup i was just being dumb, is there any way to get bukkit and fabric on the same server?

**Comment by apace100** [comment]
I'm not sure, but in my Discord server I heard of people talking about Paper, which apparently combines Fabric with plugin frameworks such as Bukkit.
As I said, I'm not sure, but you could try looking that up to see if it's what you need.
Closing this issue now. :) Join the Discord if you need any more help!
