### ISSUE TITLE
Blaze balance

### ISSUE THREAD

**Issue by gamerjkt** [apace100/origins-fabric#183]
I had a idea on how to balance the blaze. Make it so it can swim in lava. And two make it have its own personal furnace. The furnace would only work well on fire or in lava and would cook food over time.

**Comment by apace100** [comment]
I don't think the Blazeborn really needs any improvements. The balance is fine as it is right now, therefore I won't implement these ideas in the foreseeable future.
You are welcome to create a data pack which adds these balancing changes for your own personal play though. :) [Check the wiki](https://origins.readthedocs.io/) if you want to get started with making data packs.
