### ISSUE TITLE
Power Condition

### ISSUE THREAD

**Issue by MaiTheLord** [apace100/origins-fabric#185]
I have a power
```json
{
    "type": "origins:toggle",
    "active_by_default": false,
    "key": "primary"
}
```
how can I make it available only when this condition
```json
"condition": "minecraft:entity_properties",
"entity": "this",
"predicate": {
    "location": {
        "light": {
            "light": 0
        }
    }
}
```
is true?

**Comment by apace100** [comment]
You'll have to put that condition you posted (which is a predicate) in the `predicates` folder of your data pack, and then you can reference it inside an `origins:predicate` condition ([link](https://github.com/apace100/origins-fabric/wiki/Predicate)), e.g.
```json
{
  "type": "origins:toggle",
  "active_by_default": false,
  "key": "primary",
  "condition": {
    "type": "origins:predicate",
    "predicate": "mydatapack:mypredicate"
  }
}
```
