### ISSUE TITLE
[Bug] Origins with hydrophobia can start damage taking damage for no reason

### ISSUE THREAD

**Issue by YourCommonBro** [apace100/origins-fabric#188]
I have tried to find some solution or at the very least a post with the same problem for over an hour, no results.

Switching origins does not affect it. When you switch back you start taking damage AGAIN. Please fix this, I can't play with enderian or blazeborn like this!

**Comment by apace100** [comment]
I could not reproduce this. Do you have any other mods installed? Can you share your log?

**Comment by SpinnyBoiii** [comment]
was there any chance you had particles off in your video settings menu?
that stops rain from visually showing, but the rain can still damage origins with hydrophobia.

**Comment by YourCommonBro** [comment]
> was there any chance you had particles off in your video settings menu?
> that stops rain from visually showing, but the rain can still damage origins with hydrophobia.

Ahh, that was it. Thank you very much! I'm used to playing with particles off so I never thought of it as being the problem.
