### ISSUE TITLE
Incompatible with Icarus

### ISSUE THREAD

**Issue by Appw0** [apace100/origins-fabric#191]
This is not a huge issue, but this mod's Elytrians don't play nice with [Icarus](https://www.curseforge.com/minecraft/mc-mods/icarus-fabric). It's is probably due to the different flight libraries being used by the two different mods conflicting.

I'm not asking for perfect compatibility, its just playing an Elytrian doesn't work at all with Icarus installed. The Elytrian's elytra just doesn't open, and you cannot fly unless you equip an elytra or Icarus wings. I'd be nice if you could still fly as an elytrian, even if the other mod doesn't perfectly fit with this one.

**Comment by Appw0** [comment]
Looking through other bug reports, I think this is the same/similar issue as #154

**Comment by Appw0** [comment]
Sorry to keep posting, but I've now fixed this on my fork with very little changes. Should I post a pull request?

**Comment by apace100** [comment]
Sure, open a pull-request! Thanks for fixing this. :)

**Comment by Appw0** [comment]
Here it is #195.

**Comment by apace100** [comment]
Closed. (For reasons, read #195)
