### ISSUE TITLE
Entity condition position

### ISSUE THREAD

**Issue by JDParker714** [apace100/origins-fabric#192]
Hey I'm on a pretty big smp/anarchy server based around the origins mod.  Many people are making custom origins and one  of the dev's is trying to make a power that activates when the player is above a certain y coordinate.  Currently the only idea I have is checking the block they're on and getting the block y.  However, they want this to be available when the player isnt touching a block - since the origin includes alot of levitation and stuff.  Is there an existing condition for comparing entity position - aka y position.

**Comment by apace100** [comment]
You can use in_block instead of on_block - that will also work when not
standing on a block.
