### ISSUE TITLE
Hitting boats, minecarts and similar entities with modify_damage_dealt causes local crashes.

### ISSUE THREAD

**Issue by NightmarishBlue** [apace100/origins-fabric#194]
Using the `modify_damage_dealt` power type to lower an origin's damage causes them to crash every time they punch a ridable entity, whether or not that damage is reduced to zero. 
This bug was apparently introduced in 0.6.0, and there is a log displaying the crash [here](https://gist.githubusercontent.com/natanfudge/c753e493f2fadb20663ce9c0ad6ab8dd/raw/07d5c1555438a78a92a7333f9764f5ffe6aa81c5/crash.txt).

**Comment by apace100** [comment]
Thanks, fix will be in 0.6.2 :)

**Comment by apace100** [comment]
Fixed in 0.6.2
