### ISSUE TITLE
Can't use /origin with custom origins in .mcfunction files

### ISSUE THREAD

**Issue by krysal14** [apace100/origins-fabric#198]
I have a .mcfunction file that checks if a player has a custom origin every tick with the following command:
`execute store result score @a playerOrigin as @a at @s run origin has origin @s origins:origin evolution:fire_elemental`

The problem is that this function file loads **before** the origin itself, throwing the following error:
`java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 1: Unknown origin: evolution:fire_elemental`

When reloading the data pack, the function loads and works fine using the /function command but does not execute every tick (as far as I can tell).

My log and .mcfunction files are attached below.

[origins_bug_report.zip](https://github.com/apace100/origins-fabric/files/6127388/origins_bug_report.zip)

**Comment by apace100** [comment]
This has been fixed at some point and is no longer an issue. (Sorry, forgot to close this whenever the fix for this was released.)
