### ISSUE TITLE
Cosmetic Suggestion for Immersive GUI

### ISSUE THREAD

**Issue by ConqAra** [apace100/origins-fabric#199]
When picking specific origins, I believe it'd be more immersive if the GUI was changed based on what origin you are.

Someone made a few resourcepacks add-ons doing this.

Example: https://www.curseforge.com/minecraft/texture-packs/origins-immersion-enderian

Actually, I think the creator did all of them! Here's a link to his page: [thedeaddandy](https://www.curseforge.com/members/thedeaddandy/projects)

**Comment by apace100** [comment]
Hi! Thanks for letting me know about these. I think those GUI changes look really cool.
However, after all I think changing GUIs is something that is up to the user and should be to their liking. Imagine if somebody changed all of their HUD to be in a different style and Origins would override for example the food icons. Then there'd be a clash of styles which wouldn't be very pretty.
Thus, I think that visual changes like these are up to the user and I'm not going to add them to the mod itself.
