### ISSUE TITLE
Requiem's "Mortal" and "Demon" no longer appears on the origins interface when picking origins like before

### ISSUE THREAD

**Issue by ConqAra** [apace100/origins-fabric#200]
Requiem compatibility with origins interface is gone, not appearing when choosing an origin. This worked fine before 0.6, but now does not appear. Would be nice to have it back. 

I also posted it to Requiem's github if it's not an issue from Origins: https://github.com/Ladysnake/Requiem/issues/256

**Comment by apace100** [comment]
Yeah, seems like Requiem hasn't updated to accomodate for my Origins 0.6.x update yet. :( Sorry for the inconvenience.

**Comment by ConqAra** [comment]
They have updated, no worries!
