### ISSUE TITLE
Climbing not working

### ISSUE THREAD

**Issue by dMoonShadowElf** [apace100/origins-fabric#201]
i have tried the power button its not working at all

**Comment by apace100** [comment]
Hello. I've had this bug reported from multiple sources now. However, I was completely unable to reproduce it so far...
Therefore it would be great if you could provide some additional information, such as:

1) Which version of Minecraft and Origins were you using?
2) Could you provide a log file of when this problem occurred?
3) Did it NEVER work for you on that world & with the version you're using, or did it stop working at some point?
4) Were you playing on a server or on a single player world?
5) If on a server, which version of Origins was the server running, and which other mods does the server use?

**Comment by dMoonShadowElf** [comment]
okay so 1 i am using 1.16.5
the problem only happens on origin 0.6.0 plus 
2: i will see if i can get a log
3: it works on that world and server and 1.16.5 but i have to downgrade origins as anything 0.6.0 breaks it 
4: server
5: the server has been running both the 0.6 and 0.6.1 when ur unabled to climb versions before that work fine

**Comment by dMoonShadowElf** [comment]
https://i.imgur.com/71usGGL.png
here the a screenshot of the mod folder 
Ps secret api is just https://www.curseforge.com/minecraft/mc-mods/secret-rooms-fabric
its renamed but yeah

**Comment by dMoonShadowElf** [comment]
i also like to point out i have removed bits and fullslabs as i thought they might be causing the problem
but they weren't the cause

**Comment by dMoonShadowElf** [comment]
hope that helps

**Comment by apace100** [comment]
Requiem seems to be what's causing the incompatibility
