### ISSUE TITLE
Toggle Power

### ISSUE THREAD

**Issue by ObZios** [apace100/origins-fabric#203]
I am trying to make powers that are togglable and don't know how to connect the initial 'type, active by default, key' part with the rest. 
![image](https://user-images.githubusercontent.com/80583309/111030531-af3ceb80-83fa-11eb-8aec-eb5f85605080.png)

**Comment by apace100** [comment]
Hey.
Toggle powers would be a power that's seperate from the power you want to toggle. Have a look at how "phantomize" (the toggle) and "phasing" work together in the Phantom origin.

The files can be viewed here:
https://github.com/apace100/origins-fabric/blob/master/src/main/resources/data/origins/powers/phantomize.json
https://github.com/apace100/origins-fabric/blob/master/src/main/resources/data/origins/powers/phasing.json

If you need any more help, I suggest joining the Discord - this GitHub issues board is not for help with creating data packs.
