### ISSUE TITLE
Invincibility

### ISSUE THREAD

**Issue by SpitfireWasTaken** [apace100/origins-fabric#211]
My friend hs glitched the game out and now he is invincible to everything, commands, players and mobs, I think it's because the game treats him as him still being in the origins selector menu. Is there any way to fix this?

**Comment by apace100** [comment]
This happened in versions before Origins 0.5.0 when a player joins an Origins server without having Origins installed themselves. Make sure your friend has Origins installed. If they do, they will get the origin selection menu when they join the server and after selecting an origin everything should work.
