### ISSUE TITLE
Blazeborn Bug

### ISSUE THREAD

**Issue by oi12004253** [apace100/origins-fabric#213]
when i walk on magma blocks, i start taking damage even tho i'm a blaze born. i also notice that you get hurt by a blaze fireball, i don't know if that is intentionally suppose to happen but i just want this bug to be fixed.

**Comment by apace100** [comment]
This does not happen for me. Could you provide more information, such as which other mods you're playing with, and maybe provide a log file?

**Comment by apace100** [comment]
I assume this is resolved because you didn't answer.
