### ISSUE TITLE
[Suggestion]Entity In Radius

### ISSUE THREAD

**Issue by GlitchyMess** [apace100/origins-fabric#214]
I'm trying to make a Dragon Origin using datapacks and i can't find a condition that checks if theres an entity nearby , so i want to suggest this condition to you.
It is just like Block in Radius :
-
**entity_condition**
**radius**
**shape**
**comparison**
**compare_to**
-
If there is already a condition that does that , pls tell me and ill delete this suggestion

**Comment by apace100** [comment]
You can use the command condition for this. Check the example on the
command condition page in the wiki. :)

**Comment by GlitchyMess** [comment]
Oh i'm dumb and didn't notice that one , sorry
i'll delete this then
