### ISSUE TITLE
A few Origin Suggestions.

### ISSUE THREAD

**Issue by CJPsalm139** [apace100/origins-fabric#217]
Red Dragon: Abilities (Origins Mod)

Gameplay Impact: 3
Spawns in Nether
Abilities: 
Hothead: Strength I in the Nether
Fire Resistant: Low damage from hot things
Lavawalker: Does not sink in lava
Ignition: Light entities on fire with melee
Impaired: Slowness and Weakness II in the rain, IV in water.
Boiling: Takes 2x damage from water-related attacks. (i.e. Guardian Rays, Tridents, etc.)

Gameplay Impact: 2
Blue Dragon: Abilities
Aquatic: Permanent Respiration V and Depth Strider III
Speed III and Strength I in rain or water as well as Dolphin's Grace
Takes half damage from aquatic mobs or weapons
Rainman: Compounded Impaling V on all ranged attacks
Made Of Water: Takes 2x fire damage
Puts out fire by walking over it but still takes damage
Slowness II and Weakness III in the nether
Aquatic: Cannot eat land food

Vindicator:  
Gameplay Impact: 2
Appearance: Skin is greyscale
Abilities: 
Johnny: Does 2x damage with an Axe.
Disciple: enchantments on weapons can go 2 levels higher, as the knowledge was passed down from the Evokers.
Brotherhood: Illagers are neutral.
Two-Handed Weapons: Can't use a shield when holding an Axe.
Unpopular: Villager trades are double price, and Iron Golems attack on sight.
Tamed: Ravagers are neutral

Evoker: 
Gameplay Impact: 3
Appearance: Skin is greyscale.
Abilities: 
Claws: Can summon evoker claws that attack the nearest enemy within 1 chunk.
Undying: Player is gifted a Totem of Undying for every 24hrs they are on the server/world (Can be tracked in Statistics)
Necromancer: Can summon 3 vexes to fight for you for 30 seconds, after which they will die.
Brotherhood: Illagers are neutral
Unpopular: Villager trades are double price, and Iron Golems attack on sight.
Tamed: Ravagers are neutral

Pillager: 
Appearance: Skin is greyscale
Gameplay Impact: 2
Abilities: 
Archer: 2x Damage and arrows have a less RNG accuracy when fired
Tamed: Ravagers are neutral
Brotherhood: Illagers are neutral
Pillaging: Can't trade with villagers, but if you punch them, they have a chance to randomly give you an item from their trade list, even if it hasn't been unlocked yet. 

Illusioner:
Gameplay Impact: 1
Appearance: Skin is greyscale
Abilities: 
Magic: Can turn invisible for 30 seconds every minute. Can Summon 5 NPC Clones of yourself for 1 minute every 5 minutes. 
Vaccinated: You've studied how to make yourself immune to toxins which allows you to be unaffected by debuff potions that have been thrown from a player or mob.
Unknown: All mobs avoid you because they don't know what you are.

Ravager: 
Appearance: Horns, and darker greyscale than Illagers
Abilities: 
Horned: Running into enemies cause 3 True Damage
Tameable: One player can ride on top of you should you let them, however you can press LSHIFT to knock them off.
Bulky: +8 damage with melee attacks
Armor: +75% damage reduction if not wearing any armor

Canine: 
Gameplay Impact: 2
Abilities: 
Savage: Skeletons run away from you
Hunter: Permanent speed II and strength II
Carnivore: Better saturation and hunger from raw meat as well as 0.25x saturation and hunger from vegetables or fruits
Puppy: Half health of regular players
Allergies: Wither II effect for 30 seconds when eating cookies

Vex: Replaces phantom class as well as: 
Flight: Can use Elytra Flight for 20 seconds after jumping from Y = 200 or higher
Spirit: Deal Damage by passing within the hitbox of your enemy while invisible/intangible

Phantom: 
Gameplay Impact: 3
Abilities: 
Ghostly: Chainmail Armor becomes invisible with you and can't wear more than chainmail armor
Undead: Cannot eat food, Low saturation, Burns in daylight unless invisible, Cannot Drown, Permanent Full Hunger
Harming Potions heal, healing potions harm
Felinophobia: Cats hiss at you, you cannot tame them
Lightweight: Can't wear more than chainmail armor, No Fall Damage 
Nocturnal: Speed IV, Strength II, & Night Vision or in place with a light level of 3 or less
Kinetic Energy: Does 7 True Damage when moving through the hitbox of opponents, and cannot wield any weapons. Cannot be invisible when attacking. If on fire, this will light your opponent on fire as well.

Creeper: 
Gameplay Impact: 2
Abilities: 
Combustion: Can explode, but this removes 16 health regardless of type of armor or enchantment level or any potion effect
Group Mentality: Creepers are neutral to you
Leaf: Reduced Damage from explosions(But not your own)
Camouflage: Players can only see your nametag from 1 chunk away
Creeping: Walks Silently
Felinophobia: Cats hiss at you, You cannot tame cats
Arthropod: Take extra damage from Bane Of Arthropods Weapons

Skeleborn:

Gameplay Impact: 3
Abilities: 
Archer: Double Damage with ranged weapons
Hollow: Projectiles go through you
Master Archer: Double enchantments on projectile weapons
Undead: Cannot Drown
Strayed: Chance for arrows to be slowness when fired or crafted
Undead: Burns in daylight without helmet
Bone Fide: Takes 1.5x damage from melee
Undead: Takes damage from Health potions

Zombie: 

Gameplay Impact: 2
Strengths: 
Respawn: Chance to keep armor on death
Drowned: Chance to respawn with a trident of varying power
Once-Human: Strength II in Water or Warm Biomes
	    1.5x melee damage
Undead: Hostile Mobs are neutral to you 
	Burns in Daylight without helmet

Slimespawn: 
Appearance: Greenscale skin
Gameplay Impact: 3
Abilities: 

Magma: No Fire Damage
Bouncy: No Fall Damage, but bounce when hitting a block after falling
Elastic: Can Jump 4x higher than humans
Monster: Hostile Mobs are neutral to you									
Bouyant: Cannot sink in lava or water
Absorbing: Cannot eat food. You gain health by killing mobs or players and absorbing their drops. You still acquire the drops.

Arctic: 

Gameplay Impact: 3
Strengths: 

Pescatarian: Can only eat fish, and 3x hunger and saturation from salmon
Padded: Cannot freeze or sink in powder snow
Bulky: 2x as strong as regular players
Swimmer: 2x as fast as regular players in water
Furry: Weakness IV in warm biomes
       Weakness I in temperate biomes

Vulpine: 

Gameplay Impact: 2
Abilities: 

Strong Legs: Permanent Jump Boost II
Omnivore: 2x saturation and hunger from raw Chicken, Rabbit, and Sweet Berries
Short Legs: 3x faster than normal players
Hated: Wolves attack you

Villager: 

Gameplay Impact: 4
Strengths: 

Relative: All villager trades 25% price
Regular Customer: Reputation permanently at +40
Friendly: Villagers will be lured by emeralds
	  Naturally Spawned Golems will be peaceful to you 
Pacifist: Can't melee hostile mobs (Can punch them, it won't do damage), can also use ranged weapons such as thrown trident, potions, or bows/crossbows.

Witch: 
Gameplay Impact: 
Abilities: 

Taboo: All Villager Trades 50% higher
Annoyance: Iron Golems attack on Sight
Studied: Pressing R will apply a random buff potion effect for 10 seconds at a time, with a cooldown of 15 seconds. However, this does not work if a potion effect is already in use. 
Pressing O will throw a random debuff potion of ANY effect that applies the effect for 10 seconds, with a 120 second cooldown.
Fashion: All Wearable Head Items look like Witch's Hats when you wear them.

**Comment by apace100** [comment]
This is not the place for Origins suggestions. You can join the Discord server (linked on the CurseForge page) and post your suggestions there, if you haven't already.

**Comment by CJPsalm139** [comment]
Oh. Okay.
