### ISSUE TITLE
Inchling Climbing Visual

### ISSUE THREAD

**Issue by SirCaptainCaleb** [apace100/origins-fabric#22]
When an inchling climbs in third person view, the camera zooms in on the head, making it so you can't see anything. This makes climbing difficult, even though it is essential for inchlings.

**Comment by apace100** [comment]
I contacted the author of Extra Origins about this (MoriyaShiine), but they said they probably won't be able to fix this, because it is some kind of vanilla bug, and not a problem on their end. Sorry.

**Comment by SirCaptainCaleb** [comment]
Okay. Maybe I'll try to fix it myself when I get some spare time. I don't really understand it being a vanilla bug, though - When I am in third person vanilla, and I climb, I don't get any zoom-in effect
