### ISSUE TITLE
You should be able to craft a orb of origin or some form of way to get a different origin without commands or creative

### ISSUE THREAD

**Issue by 0-Red** [apace100/origins-fabric#221]

**Comment by MineRobber9000** [comment]
From the Discord server:

> Want your own Orb of Origin recipe?
> Create it easily using https://crafting.thedestruc7i0n.ca/
> 1) Click Add Item in the top right
> 2) Enter origins:orb_of_origin as the id
> 3) Enter whatever name
> 4) Click add
> 5) Use new item with pink and black texture as recipe result (just drag it over)
> 6) Drag and drop the crafting recipe you want
> 7) Download as datapack :)

**Comment by apace100** [comment]
This is not going to happen, as Origins for me are about making a choice and sticking with it for the entire run / world. It wouldn't make sense if you could change what you are, if you know what I mean. Additionally, as MineRobber9000 said, it's easy enough to make it obtainable yourself with a data pack.
