### ISSUE TITLE
Polish translation.

### ISSUE THREAD

**Issue by RDKRACZ** [apace100/origins-fabric#232]
I would like to contribute by adding it but how? So far I only translated by Poeditor and Crowdin. Here I suppose I need to make a pr?

**Comment by apace100** [comment]
Hi. Yes, the way it's done right now is you just take the `en_us.json` from the file, translate it, and send it to me. You can either send it to me on Discord, make a PR, or post the file here. Whatever works best for you. And send your name with it, so I know how to properly credit you on the CF page. :)

**Comment by apace100** [comment]
(Will merge it in 0.7.1)
