### ISSUE TITLE
How do I add a secondary keybind?

### ISSUE THREAD

**Issue by sakisiil** [apace100/origins-fabric#239]
I have 2 powers on my custom origin with the "active self" command, but how do i separate them? I can't just use G for both of the powers. There was something on the wiki, but i didn't quite understand it, so can anyone tell me the exact code needed for, idk, letter H? It would help a lot!

**Comment by SpinnyBoiii** [comment]
https://github.com/apace100/origins-fabric/wiki/Key

https://github.com/apace100/origins-fabric/wiki/List-of-keybindings
