### ISSUE TITLE
Add a "execute_after" field to Power Types.

### ISSUE THREAD

**Issue by Hmvss** [apace100/origins-fabric#251]
Just a simple field "execute_after", that execute "entity_action" after self execution.

Just like that:
{
    "type": "origins:active_self",
        "entity_action": {
            "type": "origins:add_velocity",
            "y": 10
        },
        "cooldown": 100,
        "key": {
            "key": "key.origins.secondary_active",
            "continuous": false
        },
        "execute_after": {
            "entity_action": {
                "type": "origins:execute_command",
                "command": "particle minecraft:dust 10 5 5 0.5 ~ ~1 ~ 0 0 0 1 10",
                "permission_level": 2
            }
        }
}

**Comment by Hmvss** [comment]
Or probably execute a passed power/subpower instead of a "entity_action"

**Comment by apace100** [comment]
You can use the `and` action [(link)](https://origins.readthedocs.io/en/latest/meta_actions/and) to combine multiple actions (they will be executed in order). If you need a time difference between the actions you want to execute, you can use a `delay` [(link)](https://origins.readthedocs.io/en/latest/meta_actions/delay/) action.
