### ISSUE TITLE
Failed to connect to the server this sever requires you to install the Origins mod (v0.7.0) to play

### ISSUE THREAD

**Issue by ShadowDaFoox** [apace100/origins-fabric#257]
My friend has all of the same mods as me including origins and it works for me but it keeps saying "Failed to connect to the server this sever requires you to install the Origins mod (v0.7.0) to play"  for my friend

**Comment by apace100** [comment]
Then they probably didn't install the mods correctly.
They can confirm by creating a single player world. If the Origin choice doesn't show up there, they don't have Origins installed.
