### ISSUE TITLE
[Bug] dimension_distance_multiplier doesn't apply properly if the multiplier isn't an integer

### ISSUE THREAD

**Issue by The13thEmpire** [apace100/origins-fabric#258]
Game Version: 1.16.5
Mod Loader: Fabric 0.11.3
Mod Version: 0.7.0 

The dimension_distance_multiplier for the power type modify_player_spawn does not apply properly if the multiplier is not an integer. Any value below 1 gets rounded to 1 and any non integer value above 1 gets rounded down.

**Comment by apace100** [comment]
Fixed in 0.7.2. :)
