### ISSUE TITLE
Avians are sinking slower than Humans

### ISSUE THREAD

**Issue by GeeLeonidas** [apace100/origins-fabric#26]
I don't know if this is intended or not, but I noticed that, as an Avian, I was almost not sinking when underwater. Technically, birds are less dense than people, so it makes sense for them to sink slower (or to float) due to buoyancy. I'm just reporting this because, if it is a feature™, it should be part of the power list.

Video:
[https://streamable.com/9ygc14](https://streamable.com/9ygc14)

**Comment by apace100** [comment]
Thanks for making me aware of that. Yeah, that's just a side effect of the slow falling effect. I don't think I'm gonna add it explicitly to the power list though - it's the same effect you get with a vanilla slow falling potion. And, at the same time, it's still different from the Merling's "Like Water" power, which actually makes you not sink in water.
