### ISSUE TITLE
Custom power not activating - what did I do wrong?

### ISSUE THREAD

**Issue by MechanosG** [apace100/origins-fabric#260]
Heya.  So long story short, reviving a modpack that burned me out, to make something for a group of friends to play with.  Trying out Origins, and it's pretty cool.  But I'm wanting to customize the default races.  I figured out how to do so via datapack and using kubejs to load it, and confirmed that the stuff I add is loading.  That said...  for some reason I cannot figure out how to add an effect to a race.  More specifically...  the stock night vision for merlings isn't real night vision and just increases brightness.  But our modpack uses a darkness mod which allows light level to go pitch black.  Merling night vision doesn't actually affect light level, so it effectively does nothing.  I tried to aid this by adding this power -

```
{
  "type": "origins:action_over_time",
  "entity_action": {
    "type": "origins:apply_effect",
    "effect": {
      "effect": "minecraft:night_vision",
      "duration": 6000,
      "amplifier": 0,
	  "show_particles": false,
	  "show_icon": true
    }
  },
  "interval": 10,
  "falling_action": {
    "type": "origins:clear_effect",
    "effect": "minecraft:night_vision"
  },
  "condition": {
    "type": "origins:submerged_in",
    "fluid": "minecraft:water",
    "inverted": false
  }
}
```

I named it fish_vision.json, and I added it to the merling.  I intend to set show_icon to false once I confirm it's working, and the duration is set that high just in case the night vision starts fading in and out from using a small number.  But for some reason, this power does nothing.  I know the file is "trying" to load, because earlier when I accidentally left in an extra bracket, it errored in the console and decided to skip it when loading merlings.  Then after I fixed it, the error went away.  But still no night vision effect.  So I assume I'm just doing this wrong?

MC 1.16.5
Origins 0.7.0
Yes, I have replace set to true in the origin layers (found out about that the hard way when I cloned all the base races and got really confused lol)

**Comment by apace100** [comment]
First off: Merling night vision _is_ real night vision, just without the potion effect. However there's an incompatibility with the TrueDarkness mod which causes the night vision powers to not work properly when that mod is installed. ;)

Now to your problem:
The power looks fine to me, so I can only think of one thing without seeing the rest of the pack: Did you also add the power to your origin?

Anyway though, this issue board is not intended for help with data packs. Please use [the wiki](https://origins.readthedocs.io/en/latest/) for general information or [the Discord server](https://discord.gg/4mTMHu3) for support with data packs.

**Comment by MechanosG** [comment]
1. Usually darkness mods only change the minimum light level.  Seems strange that it would be incompatible with your night vision if you're using vanilla night vision (toggling it, you can see something is happening, but dark areas don't get any brighter).  Potions of night vision work however.  Does this mean TrueDarkness also changes night vision potions, and Origins is unable to access the night vision effect after?

2. Yes, I added the power to the origin.
```
{
	"powers": [
		"origins:water_breathing",
		"origins:water_vision",
		"origins:fish_vision",
		"origins:aqua_affinity",
		"origins:swim_speed",
		"origins:like_water",
		"origins:aquatic",
		"origins:conduit_power_on_land",
		"origins:air_from_potions"
	],
	"icon": {
		"item": "minecraft:cod"
	},
	"order": 0,
	"impact": 3
}
```
This is merling.json.  Notice the fish_vision entry.

3. Lastly, if you refuse to help me here, I won't be able to get help, unless you prefer I use CurseForge comments (most devs don't).  I've already used the wiki to get this far, yet things aren't working as expected.  I will not be joining any Discords, as that always ends up a recipe for disaster.  Aka, popularity contests, arbitrary rules used to ban people (sometimes for censorship), or just being ignored if no one particularly feels helpful any given day.  Etc, the usual Discord nonsense.
