### ISSUE TITLE
All cobwebs (including ones placed by the player) cannot be destroyed while using the Arachnid origin

### ISSUE THREAD

**Issue by AnthonyFic-code** [apace100/origins-fabric#262]
Cobwebs don't have a hitbox when using arachnid origin
![image](https://user-images.githubusercontent.com/76977714/115928099-9725a680-a453-11eb-920f-0cd03f19f86c.png)

**Comment by apace100** [comment]
This is not a bug, it's a feature. It allows Arachnid players to punch through cobwebs with ease, and theoretically live in a house completely filled with cobwebs, for example.

To enable the hitbox, all you have to do is sneak.
