### ISSUE TITLE
Custom power not working - How do I fix it?

### ISSUE THREAD

**Issue by Nuggetzilla** [apace100/origins-fabric#263]
Hello! I am fairly new to the coding scene [I started literally 5 days ago], and I was wondering why this custom power isn't working. I've been doing extensive research but I generally cannot figure it out. I might just be dumb though.
But here's the code I wrote;
{
    "type": "origins:active_self",
    "entity_action": {
        "type": "origins:stacking_status_effect",
        "min_stacks": 0,
        "max_stacks": 1,
        "duration_per_stack": 40,
        "effect": {
            "effect": "minecraft:levitation",
            "duration": 1,
            "amplifier": 2,
            "show_particles": false,
            "show_icon": true
        }
    },
    "name": "Flappy",
    "description": "Happy Flappy!"
}

- I'm trying to make it so when you activate your power you get the levitation effect and you go upwards, yet every time I've tried this the ability doesn't show up nor does it work.
I was wondering if anyone was able to help me out with this? Or at least explain how to do it.

**Comment by apace100** [comment]
`stacking_status_effect` ([wiki link](https://origins.readthedocs.io/en/latest/power_types/stacking_status_effect/)) is not an entity action type, it's a power type. What you'd be looking for is the [apply effect action](https://origins.readthedocs.io/en/latest/entity_actions/apply_effect/).

Anyway, this issue board is not intended for help with data packs. Please use [the wiki](https://origins.readthedocs.io/en/latest/) for general information or [the Discord server](https://discord.gg/4mTMHu3) for support with data packs.
