### ISSUE TITLE
connection issues?

### ISSUE THREAD

**Issue by ZenpaiZ** [apace100/origins-fabric#265]
i put the exact same mod in my server logs and my mod folder on java and it says i need the same exact version i have, im confused, is there a reason for this? im using shockbyte as my server host.

**Comment by kiaric** [comment]
I find myself having the exact same issue trying to connect to a friend's server

**Comment by ZenpaiZ** [comment]
> I find myself having the exact same issue trying to connect to a friend's (self hosted) server.

i found out my problem, it was that i was using forge instead of fabric while loading up minecraft, i hope this will help
