### ISSUE TITLE
"origins:modify_xp_gain" doesn't function properly when using a negative modifier.

### ISSUE THREAD

**Issue by ShareYourHead** [apace100/origins-fabric#269]
I am trying to make a power that makes it so you gain XP 25% slower. The code was very straight forward (only 7 lines, 4 of which had more than one character), but upon testing in-game, it doesn't seem to work right. I tended to gain a very inconsistent amount, but usually more around the realm of 60% slower. Sometimes if I had been in contact with multiple xp orbs for too long, I would cease to gain any XP

**Comment by apace100** [comment]
Fixed in 0.7.2. :)

**Comment by ShareYourHead** [comment]
thanks!
