### ISSUE TITLE
/origin command doesn't trigger onChosen

### ISSUE THREAD

**Issue by MerchantPug** [apace100/origins-fabric#271]
I noticed this issue whilst testing my own addon, it actually broke something I added so I used mixins to change this. However I personally want to avoid interfering with the original mod code so I'll throw this oversight here.

I may provide my own pull request to fix this however I'd like to check if it's an oversight as opposed to being intentional before I do so.

For example this allows the command to give an Elytrian better than Chainmail armour provided they don't take it off:
![image](https://user-images.githubusercontent.com/81167232/116732880-b1045200-aa2e-11eb-8637-3fc87a1af330.png)

**Comment by apace100** [comment]
Fixed in 0.7.2. :)
