### ISSUE TITLE
Power-Influencing Commands for Individuals

### ISSUE THREAD

**Issue by jbjornberg** [apace100/origins-fabric#272]
Would it be possible to make a command that grants powers to specific individuals and not their entire origin?
For example, if I had two Merlins and one of them completes a quest in FTBQuests where they kill a Puffer-Fish- I might want them to have the custom poison thorns ability I made. But I wouldn't want the other Merlin to also have this power.

In the first place- would it even be realistically possible to add powers without a full server restart?

**Comment by apace100** [comment]
This is definitely in the realm of possibilities. However it would require a major rework of how the current system works. But this rework is something I was planning to do anyway. That I want to do it however doesn't mean that I will, and even if I'm going to work on it, it would take a long time. I hope you understand that this feature is not going to be implemented in the near future.

**Comment by jbjornberg** [comment]
Completely understandable. Thank you for the clarification, for now I'll keep doing the manual re-adjustment system I've been doing. I will eagerly await when I am able to release my dynamically power-awarding quests.

**Comment by jbjornberg** [comment]
Thanks for adding this to 1.17! Do you think this will be back-ported to 1.16.5?

**Comment by apace100** [comment]
Oh, completely forgot to notify you on this issue when I did the 1.17 update!
Sadly, due to the large amount of changes I made for the 1.17 update, backporting this would mean a lot of work for me. Therefore I won't be backporting that feature (or any other features, for that matter).

**Comment by jbjornberg** [comment]
No problem haha, I was just casually checking out your 1.17 update and saw the power command and freaked out xD
I can only hope FTB Quests updates to 1.17 soon though, hoping to automatically give players powers upon completing certain quests. It would also open up doors for "power exchanges" where players can remove powers in exchange for new ones, or something like that lol.

Thanks again for adding this!!
