### ISSUE TITLE
Update cardinal components to the newest version to avoid crash

### ISSUE THREAD

**Issue by calloatti** [apace100/origins-fabric#276]
Origins crashes with the latest version of Fabric API when creating a new world

https://paste.ee/p/uNsWl

Downloading the newest version of cardinal components fixes the crash: https://www.curseforge.com/minecraft/mc-mods/cardinal-components/files/3295352

https://paste.ee/p/MpoPs

**Comment by apace100** [comment]
Will be done in 0.7.1, so you don't have to do it manually. Thanks.

**Comment by apace100** [comment]
Fixed now in 0.7.1 :)
