### ISSUE TITLE
World generation freezes with origins mod

### ISSUE THREAD

**Issue by poopman97** [apace100/origins-fabric#279]
When i create a new world or load a existing it gets to 1-5% and stops generating the graphical image of the world ggenerating is comolete but just with tiny holes. I don't have a crash report becuse minecraft didn't crash i just didn't do anything. Im using windows 7 with fabric api, optifabric and mod menu mods.

**Comment by superon** [comment]
fabric api 0.34.0?  if so use 0.33.1

**Comment by apace100** [comment]
Exactly. Will be fixed in the next update of Origins, probably tomorrow.

**Comment by poopman97** [comment]
Ok thanks a lot! :-)
