### ISSUE TITLE
Elytrian Powers

### ISSUE THREAD

**Issue by rileynr** [apace100/origins-fabric#28]
I abso-freaking-lutely love this mod, and if there is no solution to my current predicament that's fine!

I'm currently playing an Elytrian and have platforms leading up to my sky base (about 8 of them) that can only be glided to with an Elytrian's bounce power and elytras. However, because the cooldown on this ability is about thirty seconds it certainly takes a while to climb all the way up. Is there a way to change how long it takes in config files or something similar? A command I can use?

It's a purely selfish question for my build... if it can't be helped by me, a player with no knowledge of how mods actually work, then I'll just make do and appreciate all of the wonderful features the mod has anyways.

**Comment by apace100** [comment]
Right now, it's not easily possible with a config file or something similar. Your only option is to download the source code, change the number for the cooldown in the code (file power/PowerTypes.java, line 133, where it says 20 * 30), and build a new .jar for the mod yourself. This is probably a lot of effort you do not want to go through if you have no experience with modding or programming.

I'm currently working on a big change to Origins though, where powers will be data-driven. This means that every power will be defined by a json file, and also be configurable there by overriding the existing json files with a data pack.

I will contact you again once this is possible.

**Comment by rileynr** [comment]
Thank you so much! ^-^

**Comment by apace100** [comment]
Doable now by providing a data pack which overrides the `launch_into_air` power!
