### ISSUE TITLE
Map loading freezes at a certain percentage.

### ISSUE THREAD

**Issue by livelyeko** [apace100/origins-fabric#280]
For some reason, the Origins mod is causing the map loading screen to freeze. 

Here is the log: https://drive.google.com/file/d/1-VeZS9wmphIh9dTDVQhD_FgCFDsrdFTS/view?usp=sharing

**Comment by ama-yuh** [comment]
This was happening to me and I downloaded this and it works fine now.  https://www.curseforge.com/minecraft/mc-mods/cardinal-components/files/3295352

**Comment by apace100** [comment]
Fixed in 0.7.1 :)
