### ISSUE TITLE
modImplementation for addons is no longer functional

### ISSUE THREAD

**Issue by MerchantPug** [apace100/origins-fabric#288]
This effects both Origins mod and FallFlyingLib.

Bintray shut down download link functionality recently and because of this mod developers are unable to download these two mod sources to their workspace.

See for FallFlyingLib fix:
#286

**Comment by MerchantPug** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'toomanyorigins'.
> Could not resolve all files for configuration ':modImplementation'.
   > Could not resolve com.github.apace100:origins-fabric:v0.7.1.
     Required by:
         project :
      > Could not resolve com.github.apace100:origins-fabric:v0.7.1.
         > Could not get resource 'https://dl.bintray.com/adriantodt/maven/com/github/apace100/origins-fabric/v0.7.1/origins-fabric-v0.7.1.pom'.
            > Could not GET 'https://dl.bintray.com/adriantodt/maven/com/github/apace100/origins-fabric/v0.7.1/origins-fabric-v0.7.1.pom'. Received status code 403 from server: Forbidden

For a bit more context this is what happens when I try refreshing the dependencies of the mod.

**Comment by adriantodt** [comment]
Currently, I'd recommend switching to Jitpack for now... We're looking into doing our own Maven but it's not our main priority, and Jitpack works fine.

**Comment by apace100** [comment]
Fixed in 0.7.2. :)

**Comment by NotJustAnna** [comment]
Just a small update in our part: the Cafeteria Development Team finally managed to set up our own Maven Repository, so expect FallFlyingLib to be released from now on.
