### ISSUE TITLE
Water damage to blazeborns seems to be delayed

### ISSUE THREAD

**Issue by The-Fireplace** [apace100/origins-fabric#29]
Playing with Origins 1.16.2-0.3.7, it seems that water damage from swimming and rain take at least a second or two before they start happening. I'd expect to instantly start taking damage, the same way a regular player might from stepping in lava.

**Comment by apace100** [comment]
This change will be incorporated with the data-driven power update.

**Comment by apace100** [comment]
This is now implemented, water damage is now instant for both Blazeborn and Enderian.
