### ISSUE TITLE
Origins doesn't load custom powers for custom origins (making a datapack)

### ISSUE THREAD

**Issue by shwmid** [apace100/origins-fabric#295]
Sorry if my title is vague or poor, but I'm very, very new to making datapacks for origins, and i got a little bit of it down. The custom origins *do* appear in game, but their custom powers aren't showing/working. Am I doing something wrong? I followed the CandyCaneCazoo tutorial but it still didn't work.

**Comment by shwmid** [comment]
These are the powers themselves

{
    "type": "origins:fire_projectile",
    "entity_type": "minecraft:fire_charge",
    "cooldown": 3,
    "hud_render": {
        "should_render": true
    }
	{
		"sound":"minecraft":"item.firecharge.use"
	}
}

And


{
    "type": "origins:conditioned_attribute",
    "modifier": {
        "attribute": "generic.attack_speed",
        "operation": "addition",
        "value": 9,
        "name": "A boost of strength under a primary curse influence."
    },
    "tick_rate": 20,
    "condition": {
        "type": "origins:in_rain"
    }
}

**Comment by JadeJuno** [comment]
This seems like your problem actually. I don't know if you already did, but I'd recommend going to the official Discord server for help on doing Datapacks.

**Comment by DarianLStephens** [comment]
This is very, _very_ late, and you've probably either stopped working on this or figured it out long ago, but your json is malformed.
You need a comma after every non-final element, which for list elements includes having a comma after }
