### ISSUE TITLE
Phantoms can't phase through chains

### ISSUE THREAD

**Issue by brockfernape** [apace100/origins-fabric#296]
I'm unsure if this is a bug or intended but as said the Phantom Origin can't phase through chains and me and the people on the server I play on were confused as chains are made of iron, not obsidian. 

Thanks.

**Comment by apace100** [comment]
Couldn't reproduce this - phantoms can phase through chains for me. Might be another mod conflicting, or maybe some datapack added chains to the unphasable tag?
