### ISSUE TITLE
modify_xp_gain working unpredictably

### ISSUE THREAD

**Issue by CyroxTM** [apace100/origins-fabric#300]
for some odd reason, this power doesn't function properly unless i'm using it wrong
i have it set to "multiply_total" at 0.5 which seems to be 50% somewhat at first glance but even then if a bigger amount is obtained it just messes up and gives way to much experience
I have gotten 50000 levels just from trading 6 stacks glass worth of glass panes to a cured villager (1 emerald per pane) using Merchant class somehow
Idk if this is the default mods behavior or just one of my mods causing issues?
here is a video example if it: https://streamable.com/v411gb
after testing without the mod called "fat exp orbs" i managed to get 681739 levels so it might be related to the amount of orbs or smth idk?

**Comment by apace100** [comment]
Fixed in 0.7.2. :)

**Comment by CyroxTM** [comment]
oh wow you work fast
thanks for it!
