### ISSUE TITLE
[Suggestion] Tertiary Ability Key

### ISSUE THREAD

**Issue by Diamondboy4005** [apace100/origins-fabric#301]
Simply a 4th Keybind, that adds a 3rd Power Active.

So in code it could be like

"key": "key.origins.tertiary_active"

:)

**Comment by apace100** [comment]
Probably not going to happen. If you want more keybinds, there is an add-on which provides additional active keys for Origins: https://www.curseforge.com/minecraft/mc-mods/origins-extra-keybinds
