### ISSUE TITLE
[Suggestion] /origin Check argument

### ISSUE THREAD

**Issue by Diamondboy4005** [apace100/origins-fabric#302]
When you use /origin, theres no way to find out what origin someone is without going through every origin with /origin get.

There should be an argument in the same column as get/set, which could be check.

It returns the id of their origin, so par example, bObpLayz is phantom, and when you run tye command /origin check bObpLayz, it returns origins:phantom.

Could be useful for server admins when they want to check a playera origin to make sure they're not cheating, and what theyre doing is an origin power.

**Comment by apace100** [comment]
Added in 0.7.2 which was just released. :)
Use it for example like this: `/origin get Apace origins:origin`
(The last parameter is the layer, e.g. `origins:origin` for the default layer, or for example `origins-classes:class` if you want to check the class from the Classes add-on)
