### ISSUE TITLE
Origins not working on server

### ISSUE THREAD

**Issue by PochiBuns** [apace100/origins-fabric#316]
It works on singleplayer, but not on the server we've made. The other servers in the modpack work apart from origins, both the server and the players had the same version of origins but we neither get the screen to choose our race nor does the orb or origins work. We've tried taking out the other mods (the mods remaining being origins and fabric api) but the problem still persists :(

**Comment by zzink** [comment]
Plz Help i have the same issue all the other mods work fine other than this one." it just says origins is not installed on this server" when it is.it's also the same version aswell.

**Comment by Alluysl** [comment]
There are plenty of people on the Discord server that have successfully set up a server, and there is even a channel with some useful information and a server template, so I suggest you join it so you can figure out your issue ^^

**Comment by PochiBuns** [comment]
> There are plenty of people on the Discord server that have successfully set up a server, and there is even a channel with some useful information and a server template, so I suggest you join it so you can figure out your issue ^^

Thank you so much for letting me know, I followed the server making instructions and it works now :D!
