### ISSUE TITLE
6.1 origin mod won't work

### ISSUE THREAD

**Issue by yesternight10** [apace100/origins-fabric#319]
our server has the 6.1 origins mod installed and when I try to enter Minecraft crashes with exit code 1. any solutions other than installing the newest mod update?

**Comment by yesternight10** [comment]
crash report btw:

> ---- Minecraft Crash Report ----
> // I let you down. Sorry :(
> 
> Time: 6/1/21 2:18 PM
> Description: Unexpected error
> 
> java.lang.ExceptionInInitializerError
> 	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.lambda$createEntityComponentContainer$3(CardinalEntityInternals.java:101)
> 	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals$$Lambda$4218/738015600.apply(Unknown Source)
> 	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
> 	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.createEntityComponentContainer(CardinalEntityInternals.java:86)
> 	at net.minecraft.class_1297.handler$bbi000$initDataTracker(class_1297.java:9185)
> 	at net.minecraft.class_1297.<init>(class_1297.java:263)
> 	at net.minecraft.class_1309.<init>(class_1309.java:219)
> 	at net.minecraft.class_1657.<init>(class_1657.java:199)
> 	at net.minecraft.class_742.<init>(class_742.java:45)
> 	at net.minecraft.class_746.<init>(class_746.java:141)
> 	at net.minecraft.class_636.method_2901(class_636.java:364)
> 	at net.minecraft.class_636.method_29357(class_636.java:360)
> 	at net.minecraft.class_634.method_11120(class_634.java:386)
> 	at net.minecraft.class_2678.method_11567(class_2678.java:110)
> 	at net.minecraft.class_2678.method_11054(class_2678.java:18)
> 	at net.minecraft.class_2600.method_11072(class_2600.java:21)
> 	at net.minecraft.class_2600$$Lambda$4166/1104278687.run(Unknown Source)
> 	at net.minecraft.class_1255.method_18859(class_1255.java:144)
> 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
> 	at net.minecraft.class_1255.method_16075(class_1255.java:118)
> 	at net.minecraft.class_1255.method_5383(class_1255.java:103)
> 	at net.minecraft.class_310.method_1523(class_310.java:1015)
> 	at net.minecraft.class_310.method_1514(class_310.java:681)
> 	at net.minecraft.client.main.Main.main(Main.java:215)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
> 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
> Caused by: java.lang.RuntimeException: Failed to hack fabric API
> 	at dev.onyxstudios.cca.internal.base.ComponentsInternals.<clinit>(ComponentsInternals.java:56)
> 	... 31 more
> Caused by: java.lang.NoSuchFieldException: type
> 	at java.lang.Class.getDeclaredField(Class.java:2070)
> 	at dev.onyxstudios.cca.internal.base.ComponentsInternals.<clinit>(ComponentsInternals.java:52)
> 	... 31 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.lambda$createEntityComponentContainer$3(CardinalEntityInternals.java:101)
> 	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals$$Lambda$4218/738015600.apply(Unknown Source)
> 	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
> 	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.createEntityComponentContainer(CardinalEntityInternals.java:86)
> 	at net.minecraft.class_1297.handler$bbi000$initDataTracker(class_1297.java:9185)
> 	at net.minecraft.class_1297.<init>(class_1297.java:263)
> 	at net.minecraft.class_1309.<init>(class_1309.java:219)
> 	at net.minecraft.class_1657.<init>(class_1657.java:199)
> 	at net.minecraft.class_742.<init>(class_742.java:45)
> 	at net.minecraft.class_746.<init>(class_746.java:141)
> 	at net.minecraft.class_636.method_2901(class_636.java:364)
> 	at net.minecraft.class_636.method_29357(class_636.java:360)
> 	at net.minecraft.class_634.method_11120(class_634.java:386)
> 	at net.minecraft.class_2678.method_11567(class_2678.java:110)
> 	at net.minecraft.class_2678.method_11054(class_2678.java:18)
> 	at net.minecraft.class_2600.method_11072(class_2600.java:21)
> 	at net.minecraft.class_2600$$Lambda$4166/1104278687.run(Unknown Source)
> 	at net.minecraft.class_1255.method_18859(class_1255.java:144)
> 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
> 	at net.minecraft.class_1255.method_16075(class_1255.java:118)
> 
> -- Affected level --
> Details:
> 	All players: 0 total; []
> 	Chunk stats: Client Chunk Cache: 289, 0
> 	Level dimension: minecraft:overworld
> 	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
> 	Level time: 0 game time, 0 day time
> 	Server brand: ~~ERROR~~ NullPointerException: null
> 	Server type: Non-integrated multiplayer server
> Stacktrace:
> 	at net.minecraft.class_638.method_8538(class_638.java:449)
> 	at net.minecraft.class_310.method_1587(class_310.java:2239)
> 	at net.minecraft.class_310.method_1514(class_310.java:704)
> 	at net.minecraft.client.main.Main.main(Main.java:215)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
> 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.16.5
> 	Minecraft Version ID: 1.16.5
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_51, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 697330760 bytes (665 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
> 	CPUs: 6
> 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	Fabric Mods: 
> 		autoconfig1u: Auto Config v1 Updated 3.3.1
> 		cardinal-components-base: Cardinal Components API (base) 2.7.1
> 		cardinal-components-entity: Cardinal Components API (entities) 2.7.1
> 		cloth-basic-math: Cloth Basic Math 0.5.1
> 		cloth-config2: Cloth Config v4 4.11.14
> 		extraorigins: Extra Origins 1.16.5-11
> 		fabric: Fabric API 0.34.2+1.16
> 		fabric-api-base: Fabric API Base 0.3.0+c88702897d
> 		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
> 		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
> 		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
> 		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
> 		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
> 		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
> 		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
> 		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
> 		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.6+61336ba97d
> 		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+c88702897d
> 		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
> 		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
> 		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
> 		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
> 		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.7+2868a2287d
> 		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
> 		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
> 		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
> 		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
> 		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
> 		fabric-models-v0: Fabric Models (v0) 0.3.0+bc7a746f7d
> 		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.3+e3c9d0627d
> 		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
> 		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
> 		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.5+c88702897d
> 		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
> 		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
> 		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
> 		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.2+2868a2287d
> 		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
> 		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.0+2868a2287d
> 		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
> 		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
> 		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
> 		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+2868a2287d
> 		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.6+2868a2287d
> 		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
> 		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
> 		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
> 		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
> 		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
> 		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+8183d3957d
> 		fabricloader: Fabric Loader 0.11.3
> 		fallflyinglib: FallFlyingLib 1.1.0
> 		fallingtree: FallingTree 2.10.2
> 		java: Java HotSpot(TM) 64-Bit Server VM 8
> 		minecraft: Minecraft 1.16.5
> 		moborigins: Mob Origins 1.4.0
> 		origins: Origins 0.6.1
> 		origins-classes: Origins: Classes 1.1.1
> 		pehkui: Pehkui 2.1.0+21w18a
> 		reach-entity-attributes: Reach Entity Attribute 1.0.1
> 	Launched Version: fabric-loader-0.11.3-1.16.5
> 	Backend library: LWJGL version 3.2.2 build 10
> 	Backend API: GeForce GT 710/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
> 	GL Caps: Using framebuffer using OpenGL 3.0
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fabric'
> 	Type: Client (map_client.txt)
> 	Graphics mode: fancy
> 	Resource Packs: vanilla
> 	Current Language: English (US)
> 	CPU: 6x Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz

**Comment by apace100** [comment]
Yes, I believe downgrading the Fabric API or manually installing a newer version of Cardinal Components would solve the problem as well. Not entirely sure though.
