### ISSUE TITLE
Please add some configs:

### ISSUE THREAD

**Issue by Dyschromat** [apace100/origins-fabric#32]
Mainly: deactivating obtaining an origin at the beginning of the game

Also please connect them to achievements, that way we can combine it with other mods/progression systems! :D

**Comment by apace100** [comment]
Hi! The first thing sounds like something that might be configurable with a data pack. I'll have a look at that.

Your second request is already handled! I added two advancement criteria, one for origins and one for powers. You can use these in your advancement JSONs just like all the vanilla criteria. :)

Here's a quick example of what they look like:

**Origin**
```
"criteria": {
    "chose_feline": {
      "trigger": "origins:chose_origin",
      "conditions": {
        "origin": "origins:feline"
      }
    }
  }
```

**Power**
```
"criteria": {
    "has_fragile_power": {
      "trigger": "origins:gained_power",
      "conditions": {
        "power": "origins:fragile"
      }
    }
  }
```

**Comment by Dyschromat** [comment]
Thank you so much! I really appreciate it! I want to use it combined with HQM to make questlines that unlock origins or transformations later in the game, but yeah need to prevent them from being chosen at start :)

**Comment by apace100** [comment]
You can now prevent choosing an Origin at the start, because layers can now define conditional origins. See https://github.com/apace100/origins-fabric/wiki/Origin-conditions-in-layers for more information. :)
