### ISSUE TITLE
Generic protection armor not protecting against water damage to enderians

### ISSUE THREAD

**Issue by caek08** [apace100/origins-fabric#329]
I'm not sure if this is intentional or not but enderians (and I'm assuming other origins that take damage from water I haven't tested those) still take full damage when touching water while wearing regular protection armor. I know there is water protection although it is incompatible with regular protection and in vanilla minecraft regular protection provides some protection against all damage except void damage and /kill.

**Comment by apace100** [comment]
That is intentional, because the damage taken from water ignores armor altogether. Even armor with Water Protection doesn't change the amount of damage you take, it just delays it.
