### ISSUE TITLE
0.6.3 crashes on 1.12.2.

### ISSUE THREAD

**Issue by CrankySupertoon** [apace100/origins-fabric#33]
My suggestion is to make it just for 1.12.3 and not both.

Sorry. 1.16.2 and 1.16.3

**Comment by CrankySupertoon** [comment]
https://gist.github.com/CrankySupertoon/34085b254f7e7a02a3f2d87bd3be91ce

I did also have the Origins addon installed but origins itself doesnt even load

**Comment by apace100** [comment]
Origins version 0.6.3 is only for 1.16.1, you can't use it on 1.16.2 or 1.16.3. 

The error you posted here is because Extra Origins requires the Origin version 1.16-0.3.3. If you install the correct Origins (+ Addons) for your Minecraft version, everything should work fine.
