### ISSUE TITLE
Power type "origins:creative_flight" is not defined

### ISSUE THREAD

**Issue by rbreckenridge** [apace100/origins-fabric#337]
I get the error `Power type "origins:creative_flight" is not defined`  when I try using the [creative_flight](https://origins.readthedocs.io/en/latest/power_types/creative_flight/) power. I'm using Origins mod 1.16.5-0.7.3

My power file is pretty basic:

```
{
    "type": "origins:creative_flight",
	"name": "Floot",
	"description": "Hey man, you can fly."
}
```

**Comment by apace100** [comment]
It was added in 1.0.0 (the 1.17 update). In the wiki, I suggest switching your version to 0.7.3 in the bottom right dropdown. That way you won't see features added in 1.0.0.
