### ISSUE TITLE
shulker class mining compatability

### ISSUE THREAD

**Issue by milkev** [apace100/origins-fabric#34]
is it possible for the shulker origin stone mining ability to check for the tag "minecraft:base_stone_overworld" instead of specific blocks? this would ensure compatability with mods like blockus who add 'block veins' similar to andesite and granite.

**Comment by apace100** [comment]
The mining ability uses the `origins:natural_stone` tag. If you modify that to include `#minecraft:base_stone_overworld`, it should work!
