### ISSUE TITLE
Apoli mod issue

### ISSUE THREAD

**Issue by ghost** [apace100/origins-fabric#340]
When I startup my server and login it says "this server requires the apoli mod v1.0.0 to run" or something like that

**Comment by blakecozyeah** [comment]
same have u managed to fix urs

**Comment by blakecozyeah** [comment]
> When I startup my server and login it says "this server requires the apoli mod v1.0.0 to run" or something like that

same have u managed to fix urs

**Comment by apace100** [comment]
I assume you mean this error shows when you try to join the server with your client?
That means you didn't correctly install Origins 1.0.0 on your client. Try Origins in singleplayer. If it doesn't work in singleplayer, you won't be able to join an Origins server.
