### ISSUE TITLE
Projectile entities extending ExplosiveProjectileEntity are spawned at 0 0 0 when summoned with the fire projectile power

### ISSUE THREAD

**Issue by ibarnstormer** [apace100/origins-fabric#343]
Affected origins version: 1.0.0 for 1.17

This only seems to affect entities extending ExplosiveProjectileEntity after testing. Other projectile entities such as arrows, tridents, and throwable projectiles are correctly spawned at the player position.

**Comment by apace100** [comment]
Fixed in 1.0.1
