### ISSUE TITLE
The meat tag for origin mod

### ISSUE THREAD

**Issue by Charlobo** [apace100/origins-fabric#345]
Hi, I was making a modpack and I found that origins does not have a meat tag for Farmer's delight Bon appetit. So I add the tag for them, here's the tag file I made, I hope u could add them to the official origin mod! :D

[ignore_diet.txt](https://github.com/apace100/origins-fabric/files/6667793/ignore_diet.txt)
[meat.txt](https://github.com/apace100/origins-fabric/files/6667794/meat.txt)

**Comment by apace100** [comment]
Hi. Thanks for your effort and wanting to contribute! :)
Unfortunately that's not how tags work. You would have to ask the author of the other mod to include the tag in their mod. If I include items from other mods in my mod's tags by default, the tags would fail to load unless you have all the mods installed, which is not desirable.

**Comment by Charlobo** [comment]
Thank you for responding, asking the author of the other mod to include the tag would be a huge amount of work for me, now that's the best I can do right now, sorry to disturb you. At last, have a nice day.

**Comment by Charlobo** [comment]
> Hi. Thanks for your effort and wanting to contribute! :)
> Unfortunately that's not how tags work. You would have to ask the author of the other mod to include the tag in their mod. If I include items from other mods in my mod's tags by default, the tags would fail to load unless you have all the mods installed, which is not desirable.

Thank you for responding, asking the author of the other mod to include the tag would be a huge amount of work for me, now that's the best I can do right now, sorry to disturb you. At last, have a nice day.
