### ISSUE TITLE
this f

### ISSUE THREAD

**Issue by Foesbelike** [apace100/origins-fabric#349]

**Comment by Foesbelike** [comment]
this flyfall or fallfly lib thing is causing a game crash with 1.17

**Comment by Foesbelike** [comment]
i need help and would appreciate support

**Comment by Foesbelike** [comment]
22:03:14.322
Preparing to launch minecraft client for fabric-loader-0.11.6-1.17
22:03:15.825
Checking installations.
22:03:15.840
Minecraft client fabric-loader-0.11.6-1.17 is ready to start.
22:03:15.840
Starting!
22:03:16.650
Using default game log configuration client-1.12.xml (outputs XML)
22:03:17.616
Loading for game Minecraft 1.17
22:03:17.926
The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
22:03:17.926
The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
22:03:17.937
The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
22:03:17.995
The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
22:03:18.015
The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
22:03:18.215
Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b4463c6, also found 0.3.0+a02b44633d, 0.3.0+a02b4463a0
 - Conflicting versions found for fabric-networking-v0: used 0.3.2+92519afac6, also found 0.3.2+92519afa3d
 - Conflicting versions found for fabric-networking-api-v1: used 1.0.11+b7ab6121a0, also found 1.0.11+b7ab61213d
 - Mod 'William Wythers Overhauled Overworld' (william-wythers-overhauled-overworld) recommends version 1.14.0 or later of mod modmenu, which is missing!
	 - You must install version 1.14.0 or later of modmenu.
22:03:18.224
[FabricLoader] Loading 140 mods:
	- adabraniummod@2.1.0+1.17
	- adorn@2.0.0+1.17
	- angerable-patch@1.0.0-1.16.1
	- apoli@1.0.0
	- assembly@21w06a-1.0.0
	- betternether@5.1.0
	- biom4st3r_repackaged_expressions@0.1.0
	- blockus@2.2.1+1.17
	- calio@1.0.0
	- cardinal-components@3.0.0-nightly.1.17-pre2
	- cardinal-components-base@3.0.0-nightly.21w19a
	- cardinal-components-block@3.0.0-nightly.1.17-pre2
	- cardinal-components-chunk@3.0.0-nightly.1.17-pre2
	- cardinal-components-entity@3.0.0-nightly.21w19a
	- cardinal-components-item@3.0.0-nightly.1.17-pre2
	- cardinal-components-level@3.0.0-nightly.1.17-pre2
	- cardinal-components-scoreboard@3.0.0-nightly.1.17-pre2
	- cardinal-components-util@3.0.0-nightly.1.17-pre2
	- cardinal-components-world@3.0.0-nightly.1.17-pre2
	- cavebiomes@0.6.3
	- charm@3.1.5
	- cloth-basic-math@0.5.1
	- cloth-config2@5.0.34
	- com_electronwill_night-config_core@3.6.2
	- com_electronwill_night-config_toml@3.6.2
	- com_moandjiezana_toml_toml4j@0.7.2
	- conjuring@1.0.3
	- croptopia@${mod_version}
	- culinaire@2.1
	- dark-enchanting@0.2.2+mc.1.16.5
	- dawn@2.0.3
	- dragonloot@1.0.8
	- earthtojavamobs@1.7.1+1.17
	- emerald_tools@1.2.12
	- expandedstorage@7.0.0-alpha.25
	- fabric@0.35.2+1.17
	- fabric-api-base@0.3.0+a02b4463c6
	- fabric-api-lookup-api-v1@1.1.0+1d383bb63d
	- fabric-biome-api-v1@3.1.11+c345aea83d
	- fabric-blockrenderlayer-v1@1.1.5+a02b44633d
	- fabric-command-api-v1@1.1.1+a02b44633d
	- fabric-commands-v0@0.2.2+92519afa3d
	- fabric-containers-v0@0.1.12+a02b44633d
	- fabric-content-registries-v0@0.2.2+a02b44633d
	- fabric-crash-report-info-v1@0.1.5+be9da3103d
	- fabric-dimensions-v1@2.0.10+a02b44633d
	- fabric-entity-events-v1@1.1.0+a02b44633d
	- fabric-events-interaction-v0@0.4.8+a02b44633d
	- fabric-events-lifecycle-v0@0.2.1+92519afa3d
	- fabric-furnaces@2.0.1-1.17
	- fabric-game-rule-api-v1@1.0.6+a02b44633d
	- fabric-item-api-v1@1.2.4+a02b44633d
	- fabric-item-groups-v0@0.2.10+b7ab61213d
	- fabric-key-binding-api-v1@1.0.4+a02b44633d
	- fabric-keybindings-v0@0.2.2+36b77c3e3d
	- fabric-language-kotlin@1.6.1+kotlin.1.5.10
	- fabric-lifecycle-events-v1@1.4.4+a02b44633d
	- fabric-loot-tables-v1@1.0.4+a02b44633d
	- fabric-mining-levels-v0@0.1.3+92519afa3d
	- fabric-models-v0@0.3.0+a02b44633d
	- fabric-networking-api-v1@1.0.11+b7ab6121a0
	- fabric-networking-blockentity-v0@0.2.11+a02b44633d
	- fabric-networking-v0@0.3.2+92519afac6
	- fabric-object-builder-api-v1@1.10.9+b7ab61213d
	- fabric-object-builders-v0@0.7.3+a02b44633d
	- fabric-particles-v1@0.2.4+a02b44633d
	- fabric-registry-sync-v0@0.7.10+e2961fee3d
	- fabric-renderer-api-v1@0.4.3+676f40fa3d
	- fabric-renderer-indigo@0.4.8+a02b44633d
	- fabric-renderer-registries-v1@3.2.0+a02b44633d
	- fabric-rendering-data-attachment-v1@0.1.5+a02b44633d
	- fabric-rendering-fluids-v1@0.1.13+a02b44633d
	- fabric-rendering-v0@1.1.2+92519afa3d
	- fabric-rendering-v1@1.6.0+a02b44633d
	- fabric-resource-loader-v0@0.4.7+b7ab61213d
	- fabric-screen-api-v1@1.0.4+155f865c3d
	- fabric-screen-handler-api-v1@1.1.8+a02b44633d
	- fabric-structure-api-v1@1.1.11+e36969833d
	- fabric-tag-extensions-v0@1.1.4+a02b44633d
	- fabric-textures-v0@1.0.6+a02b44633d
	- fabric-tool-attribute-api-v1@1.2.12+b7ab61213d
	- fabricloader@0.11.6
	- fallflyinglib@3.0.0-beta.2
	- fruitful@1.0.0
	- geckolib3@3.0.5
	- givemehats@1.6
	- gobber2@2.4.14
	- greater_eye@1.2.4
	- hwg@1.0.2
	- identity@1.14.0-beta-1.17
	- improved-stations@2.0.5
	- inmis@2.3.1-1.17
	- jankson@3.0.1+j1.2.0
	- java@16
	- kibe@1.7.2-BETA+1.17
	- libblockattributes_core@0.8.17003
	- libblockattributes_fluids@0.8.17003
	- libblockattributes_items@0.8.17003
	- libcd@3.0.3+1.16.3
	- libgui@4.0.0+1.17
	- libninepatch@1.1.0
	- medievalweapons@1.1.5
	- minecraft@1.17
	- moenchant_lib@0.1.0
	- moenchantments@1.17.1
	- moreberries@1.4.2
	- morevillagers-fabric@2.0.0-SNAPSHOT
	- mostructures@1.2.0-1.17
	- nbtcrafting@2.0.16+mc1.17
	- newcaves@1.3
	- omega-config@1.0.8
	- org_jetbrains_kotlin_kotlin-reflect@1.5.10
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.10
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.10
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.10
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.0
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.0
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.1
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.1
	- origins@1.0.0
	- owo@0.1
	- particle_emitter_biom4st3r@0.1.0
	- playerabilitylib@1.3.0-nightly.1.17-rc1
	- promenade@2.1.2
	- pugh_lib@1.1.3
	- reach-entity-attributes@2.1.1
	- riverredux@0.2.0
	- roughlyenoughitems@6.0.251-alpha
	- shulkerutils@1.0.1-1.17
	- simple_backpack@1.1.10
	- terraform-shapes-api-v1@1.0.4
	- things@0.2.0
	- totemmod@0.3.2
	- trinkets@3.0.0
	- universal_ores@1.0
	- upgradedshulkers@1.0.1-1.17
	- vanillaplusbiomes@0.3.2
	- william-wythers-overhauled-overworld@1.1
	- winged@1.17-3.0.0-beta.2
	- witherite@0.0.5

**Comment by apace100** [comment]
What you posted is not a crash report. There isn't really a way I can help here, unless you post an actual crash report. Either way, the library works in itself, so this is probably a conflict with one of the other mods you have installed.
