### ISSUE TITLE
Origins V0.7.3 changing protection effectiveness has no effect at total enchantment level 16+

### ISSUE THREAD

**Issue by SpinnyBoiii** [apace100/origins-fabric#351]
changing the protection effectiveness in a damage over time power type doesnt seem to actually do anything, i put the effectiveness to 0.1 for some testing purposes yet the onset delay remained the same
as a side-note, having a total enchantment level of higher than 16(possible in survival with mods such as biomemakeover) will have it act like level 16, resulting in an onset delay of 20 minutes
I don't know if this is the case for the minecraft 1.17 versions as well, as i haven't touched it yet

**Comment by apace100** [comment]
Won't fix this since I'm only gonna be working on the latest version. :)
