### ISSUE TITLE
Registry remapping failed

### ISSUE THREAD

**Issue by DEU55** [apace100/origins-fabric#352]
![asdasdadsdas](https://user-images.githubusercontent.com/86174071/122658891-44f5be80-d140-11eb-90cb-07743919b19a.PNG)
I keep getting this while trying to join my friends server.

**Comment by DEU55** [comment]
![dasdasda](https://user-images.githubusercontent.com/86174071/122660952-98bdd300-d153-11eb-8641-c8a885ad58a4.PNG)
these are the mods that my friends are using and they can get on the server easily it's just origins

**Comment by apace100** [comment]
Looks like the server is using Origins: Classes as well.
