### ISSUE TITLE
Registry remapping failed -> Enchantments error

### ISSUE THREAD

**Issue by Botatron** [apace100/origins-fabric#355]
When trying to join a origins server with my friends this message appears:

registry remapping failed: recieved id map for minecraft:enchantment contains ids unkown to the reciever! 
- moborigins:heatprotection
- moborigins:groundspikes
![Capture](https://user-images.githubusercontent.com/86250201/122795181-f6b5fc00-d2b4-11eb-974b-6a818994abdc.PNG)

I have no idea why this happens and I have been trying to find a solution for ages. Please help!

**Comment by apace100** [comment]
Hi. This is an issue with Mob Origins (an add-on, which I don't have any control over :D).
The most likely cause is that the version of Mob Origins you have on the server and the one you have on your client (if you have installed one there at all) is not the same. Please make sure you are running the exact same version of the add-on as the server you're trying to join!
