### ISSUE TITLE
Incompatable with other modded methods of adding elytra flight

### ISSUE THREAD

**Issue by milkev** [apace100/origins-fabric#356]
*latest version of origins, dragonloot, trinkets, trinkets elytra and their dependencies as of this post, as available on curseforge (06-21)

**the issue**
With mods such as dragonloot or trinkets elytra, when using their methods of activating elytra flight, they do not activate.
with dragonloots winged chestplate, the flight simply never starts.
with trinkets elytra, when the elytra is in the back slot, flight starts, but is immediately cancelled.
happens on both dedicated servers and singleplayer.
both dragonloots winged chestplate and trinkets elytra back slot work as expected when origins is not installed.
I expect this would happen with other mods which add their own elytra flight as well, but am unaware of any others available in 1.17.

**what i expected to happen**
modded methods of elytra flight to work as normal with origins installed.

**how to reproduce**
1. install origins, and either/both dragonloot and trinkets elytra
2. select any origin (except elytrian, which has an issue ill post in a couple minutes) 
3. equip winged chestplate and elytra in back slot, test them seperately (or together! gets the same result anyway)
4. watch winged chestplate not allow flight at all, and elytra in the back slot to cause the screen to jerk around a bit but not activate elytra flight
5. uninstall origins and watch these issues go away

**Comment by tehatomicpotato** [comment]
I have run into this as well with the elytrias from the better end mod. They are looking at the problem as well

**Comment by milkev** [comment]
a workaround (for now) is a datapack i made that gives you perma elytra once you have the 'find an elytra' achievment. its a bit of a cheat, but its better than not being able to use elytra without getting rid of other mods.
[Link to the Message on the Origins Discord](https://discord.com/channels/734127708488859831/749571272635187342/857351266999861258 )

**Comment by tehatomicpotato** [comment]
the normal elytras work just the modded ones dont work.

**Comment by Micalobia** [comment]
Should be fixed when #465 happens in all mods involved

**Comment by apace100** [comment]
No longer relevant since Origins uses the new Fabric API starting in 1.2.0.
