### ISSUE TITLE
World bugs out when selecting Arachnid Origin (1.17)

### ISSUE THREAD

**Issue by ghost** [apace100/origins-fabric#359]
Crashlog: https://paste.ee/p/VgwUx

It looks like other origins work fine. When selecting arachnid, mobs stop moving and the game gets stuck on 'saving world' when trying to exit.

**Comment by miraifrommars** [comment]
I had this issue too, but then i just updated my Origins mod and it started working!

**Comment by apace100** [comment]
Fixed in 1.0.1 :)
