### ISSUE TITLE
Game crashes (1.17)

### ISSUE THREAD

**Issue by Ameliaplayz** [apace100/origins-fabric#360]
listed mods
![Screenshot (626)](https://user-images.githubusercontent.com/84192828/123042327-3aca0d80-d429-11eb-828d-010e5b86af13.png)

**Comment by Ameliaplayz** [comment]
also no crash report

**Comment by apace100** [comment]
You're not using Origins in there. Why are you reporting this here? But if this is the list of _other_ mods you are using, and it crashes when including Origins, it's because of this: https://github.com/apace100/origins-fabric/issues/354

I'm closing this because it's a duplicate of that issue.
