### ISSUE TITLE
Odd hud bar bug

### ISSUE THREAD

**Issue by KutikiPlayz** [apace100/origins-fabric#361]
![2021-06-23_00 52 03](https://user-images.githubusercontent.com/73810550/123050026-74fdc580-d3bd-11eb-8b5f-b6588d641111.png)
It seems to be loading the sprite in-between the one I selected and the one after. Is anyone else getting this and/or know how to fix it? I'm on 1.17 btw.

**Comment by apace100** [comment]
I suppose this is one of the new resource bar sprites by Huang? Those have some problems, yeah, they will hopefully be fixed in the next version. :)

**Comment by apace100** [comment]
Should be fixed in the latest version.
