### ISSUE TITLE
(1.16.5) [Suggestion] Add command to change/get values.

### ISSUE THREAD

**Issue by GamyGamer** [apace100/origins-fabric#362]
As in title, I have found origin that is highly dependent on time (increasing internal value per minute)

I would like to have command that can change the values for testing purposes
command would look like this:
/origin value (Player) set/get (Namespace):(Resourcename) <value to set>

**Comment by apace100** [comment]
The /resource command does this. It works for resource powers as well as any cooldown power: https://origins.readthedocs.io/en/0.7.3/misc/commands/resource/

**Comment by GamyGamer** [comment]
oops, sorry for creating ticket for this issue, just wasn't aware of that command.

Since we are talking about /resource, is this possible to get autocomplete feature like in /origin command? (it autocompletes everything but resources names)
