### ISSUE TITLE
[Bug] Water Protection IV only lasts one second

### ISSUE THREAD

**Issue by soupyfish** [apace100/origins-fabric#364]
On the Enderian class, using one piece of water protection IV used to last around 30-40 seconds, but it has suddenly started to only last one second. I have replicated this on singleplayer, and the issue continues even after restarting my server.

These are the mods I am currently using.
![](https://cdn.discordapp.com/attachments/809554766484471848/857599105638858762/unknown.png)

**Comment by apace100** [comment]
Hm! Yes, I did want to nerf it. However I seem to have forgotten a `* 20` in the calculation. :D One piece of water protection 4 should last about 20 seconds.

**Comment by apace100** [comment]
Fixed in 1.0.3
