### ISSUE TITLE
Crashing when filling cauldron with bucket of water with Cleric Class

### ISSUE THREAD

**Issue by Cadhlawr** [apace100/origins-fabric#366]
There seems to be an issue with the Extended Potion Effect Clerics receive. This is causing a crash when trying to fill a vanilla  cauldron with a bucket of water.

[Crash report](Https://pastebin.com/3R9MJAxH) 

This is consistent across races. I tested with Human, Fox, and Bee. Other classes can use the cauldron fine.

**Comment by apace100** [comment]
Hi. This would belong on the Origins: Classes issue board: https://github.com/apace100/origins-classes/issues
However, an issue for that already exists there.
