### ISSUE TITLE
Fail building a project with Origins

### ISSUE THREAD

**Issue by MagicQuartz** [apace100/origins-fabric#372]
Every time I try to build the gradle project, it says this (the problem is related to the origins mod and I don't know what it is):
https://pastebin.com/pfHLAphL

**Comment by apace100** [comment]
That one maven repository was down (the one for Mod Menu). I now switched to the Modrinth maven to get the Mod Menu dependency. :) I suggest you do the same! Check the build.gradle in the 1.17 branch for the updated repos.

**Comment by MagicQuartz** [comment]
Thanks!
