### ISSUE TITLE
How to solve "contained unregistered power"

### ISSUE THREAD

**Issue by PeanutsLOL** [apace100/origins-fabric#377]
I was a really noob but i want to try it.And i failed here
[00:28:40.136] [Server thread/ERROR] [io.github.apace100.origins.Origins/]: Origin "calamityorigins:supremecalamity" contained unregistered power: "calamityorigins:abyssalflames"
but I do defined it.

And plz update the wiki.some of them are missing:(

**Comment by apace100** [comment]
You either didn't place the power file in the correct folder, didn't name the file correctly, or your power file has errors. Check the log for another error message explaining what could be wrong with your power if you are sure the file name and location are correct.
Your power JSON file should be located at: `data/calamityorigins/powers/abyssalflames`

Also, this issues board is not for datapack help. Please refer to the Discord server for that.
