### ISSUE TITLE
Wiki Correction

### ISSUE THREAD

**Issue by 7isenko** [apace100/origins-fabric#380]
On that wiki page: https://github.com/apace100/origins-fabric/wiki/Workspace-Setup
The repository list is outdated.
You should update it to:
```
	repositories {
		maven {
			url 'https://jitpack.io'
		}
		maven {
			name "AdrianTodt's Mod Menu" // https://www.curseforge.com/minecraft/mc-mods/modmenu
			url "https://maven.terraformersmc.com/"
		}
		maven {
			name "Reach Entity Attributes" // https://github.com/JamiesWhiteShirt/reach-entity-attributes
			url "https://maven.jamieswhiteshirt.com/libs-release/"
		}
		maven {
			name "Fall Flying Lib" // https://www.curseforge.com/minecraft/mc-mods/fallflyinglib
			url "https://maven.cafeteria.dev"
		}
		maven {
			name "Cloth Config API" // https://www.curseforge.com/minecraft/mc-mods/cloth-config
			url "https://maven.shedaniel.me/"
		}
		maven {
			name "Player Ability Lib" // https://www.curseforge.com/minecraft/mc-mods/pal
			url "https://ladysnake.jfrog.io/artifactory/mods"
		}
	}
```

**Comment by ChrysanthCow** [comment]
The GitHub wiki is no longer supported, it was moved to https://origins.readthedocs.io iirc

**Comment by 7isenko** [comment]
origins.readthedocs.io does not contain modding docs, so...

**Comment by apace100** [comment]
It is true that the GitHub wiki is outdated. The add-on guide hasn't been ported over yet though. But this issue made me put in the time to transfer it (as well as create the next guide for add-ons!).
You can find the new "Workspace Setup" guide here: https://origins.readthedocs.io/en/latest/guides/addon/workspace_setup/

Edit: if something is missing/wrong on that wiki, feel free to leave an issue or do a pull request yourself to https://github.com/apace100/origins-docs
