### ISSUE TITLE
maven.terraformersmc.com link not online

### ISSUE THREAD

**Issue by smileyplayz** [apace100/origins-fabric#381]
I am trying to run the gradle build in IntelliJ IDEA and when I run it, I get this error:

Could not HEAD 'https://maven.terraformersmc.com/me/shedaniel/cloth/cloth-config-fabric/5.0.34/cloth-config-fabric-5.0.34.pom'. Received status code 521 from server: Origin Down
Disable Gradle 'offline mode' and sync project

Unfortunately, when looking at the website, it says that it is offline.

Anyway to fix this?

**Comment by 7isenko** [comment]
Check my pull request #382

**Comment by ChrysanthCow** [comment]
You can temporarily use my fork for Origins.
https://github.com/MerchantPug/origins-fabric/tree/1.17

Just replace apace100 in the build.gradle with MerchantPug and set the version to `282d1384ff`

**Comment by Orangenal-name** [comment]
> You can temporarily use my fork for Origins.
> https://github.com/MerchantPug/origins-fabric/tree/1.17
> 
> Just replace apace100 in the build.gradle with MerchantPug and set the version to `282d1384ff`

That didn't work, but I have nothing to do with my time so I am going to try every version you have and see if any work.

**Comment by apace100** [comment]
I am now relying on the Modrinth maven for getting the mod menu dependency.
