### ISSUE TITLE
Invincibility

### ISSUE THREAD

**Issue by Orangenal-name** [apace100/origins-fabric#385]
Recently on my modded SMP, everyone randomly became invincible, and I thought earlier that it might be a mod, so I tested each mod, and when I put Origins back, I was invincible again. I have no idea why this has happened and it takes the fun out of the game. I have also tried deleting the Origins' config files, but that had no effect either.

**Comment by apace100** [comment]
Do you have datapacks installed? Do your players have Origins installed and did they pick an origin?
Players get a protection when they have an origin unchosen - this is to prevent them dying while they're in the origin selection screen.

**Comment by Aurif** [comment]
This invincibility mechanic can be quite problematic in certain situations, especially if you have an "optional" origin layer where none of the origins are choosable by the player (specific origin with subclasses, secret upgrade you need to obtain in-game). Would it be possible to disable this invincibility behaviour in such cases, just like how the view origin page and `choose` button is hidden when you can't choose anything?
