### ISSUE TITLE
Optifabric still conflicts with Origins mod

### ISSUE THREAD

**Issue by pei-pei05** [apace100/origins-fabric#386]
It says this when I try to load fabric 1.17.1:
**Found conflicting mods: origins conflicts with {optifabric @ [<=1.11.18]}**
**Creating` Empty clause ?**

Idk if I misunderstood the changelog in the latest origins file (_1.17, 1.17.1: Origins 1.0.3_) tho and origins + optifabric just dont work together but yea, this's all i know

**Comment by apace100** [comment]
The mods are currently still incompatible, but the OptiFabric dev will maybe update the compatibility again as they have done before.
