### ISSUE TITLE
Phantom phasing view 1.16.5

### ISSUE THREAD

**Issue by OlegKorsak** [apace100/origins-fabric#387]
On my server phantoms while phasing doesn't render as they should,causing them to see in blocks like normal,without blindness effect. List of mods and how phantoms see on server attached.
![photo_2021-07-19_14-16-41](https://user-images.githubusercontent.com/43847423/126152160-23cdb7b7-658f-4fca-99c5-c47ccce4c485.jpg)

![image](https://user-images.githubusercontent.com/43847423/126151860-c04f6b9b-1cbb-452a-968f-e95a73e60d50.png)

**Comment by apace100** [comment]
Hi. This is usually not a problem with mods on the server, but mods on the client. Any mods that alter rendering might be the cause. For example OptiFine is a prime example of a mod that causes this problem. Unfortunately there's not much I can do about it.

**Comment by icarusjpeg** [comment]
I had this same issue, and it turns out I had turned off the "fog" option, under video settings and details (with optifine), which is what did it.
