### ISSUE TITLE
Water Protection Enchantment Very Underpowered

### ISSUE THREAD

**Issue by AlySapphire** [apace100/origins-fabric#395]
Water Protection Enchantment only provides 0.5sec of protection per level of enchant making it weaker compared to water resistance potions, which provide up to 8mins of protection against damage of water among races who are vulnerable to water damage.

The Environmental Armour mod had a Water Protection enchantment which prior to 1.17, provided a much better level of water protection compared to the origins implementation which is quite weak and not worth trying to get for such minimal protection.

Pretty sure this is unintentional due to how little protection you get from the max level of enchantment on all pieces of armor (8 seconds if water protection IV is placed on all 4 pieces of armor).

**Comment by Alluysl** [comment]
Duplicate of #364 which was fixed in 1.0.3
