### ISSUE TITLE
BetterEnd Elytras do not work when Origins is installed

### ISSUE THREAD

**Issue by BEMZ01** [apace100/origins-fabric#396]
BetterEnd and Origins are conflicting somewhere with elytras, the elytras within BetterEnd do not activate the mods of the github repo said to post here as well, Here is the issue link > https://github.com/paulevsGitch/BetterEnd/issues/231

**Comment by AsyncBanana** [comment]
I have the same issue with armored and crystallite elytras, even when I am not using a flight-related origin.

**Comment by Micalobia** [comment]
Should be fixed when #465 happens in all mods involved

**Comment by apace100** [comment]
No longer relevant since Origins uses the new Fabric API starting in 1.2.0.
