### ISSUE TITLE
Cant join server because of "connection lost" 

### ISSUE THREAD

**Issue by NCboi** [apace100/origins-fabric#399]
My friend has a server that they host but for some reason when I try to join it doesn't work. Please help!
[Help.png.txt](https://github.com/apace100/origins-fabric/files/6886322/Help.png.txt)

**Comment by Alluysl** [comment]
Make sure you have the same exact version of each mod installed on the server and whoever joins it, Fabric really hates mods with different versions.

**Comment by ProfessorPeely** [comment]
> Make sure you have the same exact version of each mod installed on the server and whoever joins it, Fabric really hates mods with different versions.

im having the same problem, this isnt the solution, cant find anything

**Comment by Alluysl** [comment]
- Is there any error or warning while connecting that could be remotely connected to the mod within your logs? (Google how to open them if you don't know how)
- I suggest you join the Discord server so the people there can help you better c:
