### ISSUE TITLE
Blazeborn are not very well adapted to the nether (not much food)

### ISSUE THREAD

**Issue by alxpettit** [apace100/origins-fabric#4]
There's nothing to eat. Blazeborn should have the ability to eat things in the nether, besides zombie pigman flesh. Here are some suggestions:

* nether wart
* cooked nether wart? Or somesuch.
* Ooh, maybe there could be netherwart bread?
* might be a good idea to add umbral flesh blocks from Cinderscapes -- or perhaps just eating a cooked version.
* Shroomlights

**Comment by apace100** [comment]
There's not only rotten flesh - you also have the option to eat mushroom stew! Mushrooms are also farmable. If you manage to find some fossils, you have access to quite a bit of bone meal, which can accelerate mushroom growth!

As a general rule, I do not like to add content (new items, blocks, etc) to this mod. If other mods add content with more food to the Nether, you are welcome to use those!

Surviving in the Nether is difficult, I agree, but after all it's supposed to be a drawback.

**Comment by alxpettit** [comment]
Aw, okay. That's fair enough! Maybe it works better in a more vanilla-y modpack, but I found huge difficulty with my modpack, during playtesting -- like, going _hours_ without any food besides rotten flesh. I have a lot of stuff changing world generation, tho. Thinking about it, I haven't played vanilla in awhile, and it might be easier to get a hold of mushrooms in vanilla world generation.

I'll probably just make my own companion mod for your mod, for modpacks where getting hold of mushrooms is tougher! ^_^

**Comment by The-Fireplace** [comment]
I just played my first playthrough as Blazeborn, surviving in the Nether wasn't too hard once I started hunting Hoglins for porkchops.
