### ISSUE TITLE
Invalid Player Data

### ISSUE THREAD

**Issue by deftesthawk** [apace100/origins-fabric#409]
When I create a world, then save and quit that world, then reload that world I get "Invalid player data" 

After extensive testing, I have found 4 mods that have weird conflicting relationships:

Outvoted
Charm
Origins
Iris Shaders

For me to fix the issue I would have to do one of the following 2 options:
1.) Remove "Origins" Mod
2.) Remove "Iris Shaders" Mod

Unfortunately non of these options are favorable to me, as I really wanted to use these mods together.

I don't think posting my mod list would be much help as I've got 200+ mods installed, this is the last issue with my pack.

Minecraft version 1.17.1 
Origins version 1.0.3

**Comment by deftesthawk** [comment]
I forgot say how to repeat:

Load world with mods installed, then save and quit to the menu, finally load the world again

**Comment by deftesthawk** [comment]
Just found out that there's another mod causing the conflict will comment when I have more info

**Comment by deftesthawk** [comment]
The 3rd conflict is Iris Shaders

Which sucks because all the conflicts are mods I  don't want to remove :(

**Comment by deftesthawk** [comment]
lol there's a 4th conflict

**Comment by deftesthawk** [comment]
let's hope this is it. I'll delete the previous message spam and compact my findings into 1 message.

to recap there's a 4-way conflict with:
Origins
Charm
Iris Shaders
PlayerAbilityLib

Whenever I load a world that has previously been loaded with these mods I get the error "Invalid Player Data"

Removing any of the 4 fixes the issue so I'm going to remove the "PlayerAbilityLib" Mod

**Comment by deftesthawk** [comment]
I have edited my post to contain my final results from testing.

**Comment by deftesthawk** [comment]
After further testing, it seems when I have Iris Shaders and origins installed together it doesn't like it when I put stuff in my inventory from certain mods.

**Comment by deftesthawk** [comment]
After spending a lot of time testing I have come to the conclusion that origins doesn't play well with other mods when you have shaders enabled as I'm getting the same issue as someone else when I have Iris shaders installed instead of optifine. Whenever I put stuff in my inventory from multiple mods with shaders enabled and origins installed reloading the world will cause this error to appear

**Comment by SigmaScorpii** [comment]
I can confirm that Shaders or anything else are not even needed.
All broken files suddenly go valid when the Origins mod is removed.

The issue also shows in Singleplayer worlds.

Log files don't show anything strange or anything that went wrong.

**Comment by SHXRKIEgg** [comment]
I tested and found that the Mod Charm is causing Invalid Player Data with Origins. The specific fix is to change the Charm Config "AutomaticRecipeUnlock Enabled" = true to false.

**Comment by deftesthawk** [comment]
Thank you, that allows me to use it in my mod pack :D

**Comment by itsdinkd** [comment]
This doesn't fix it for me..

**Comment by apace100** [comment]
Should be fixed with the newest version (1.1.0, released yesterday)
