### ISSUE TITLE
Elytrian can equip heavy armour when right clicking it to replace a piece of armour already equipped.

### ISSUE THREAD

**Issue by Mnky313** [apace100/origins-fabric#410]
Easier to describe by just saying how me noticed it.

If you're an elytrian wearing chainmail (or presumably any other armour), holding a piece of armour in your hand that can't normally be equipped and right clicking will equip it anyway and put the chainmail you previously had equipped in your hand.

**Comment by tehatomicpotato** [comment]
This doesn't work?

**Comment by apace100** [comment]
In vanilla you can't swap armor like that, therefore this is an incompatibility with some mod you have installed which allows that
