### ISSUE TITLE
elytra trinket not working in 1.17

### ISSUE THREAD

**Issue by xelye** [apace100/origins-fabric#416]
heyyy im having issues with my eyltra not working when its in the back trinket slot, this only happens with origins, even if my origin has nothing to do with an elytra D:

trinkets = https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric

**Comment by HatTrkPatrk** [comment]
https://www.curseforge.com/minecraft/mc-mods/elytra-trinket-fabric

**Comment by GoofBallBoi** [comment]
Have you tried pressing the H button

**Comment by xelye** [comment]
pressing H didn't fix it :c i also checked to make sure i was using the updated versions of both origins and elytra trinket but im still having issues :<

**Comment by Micalobia** [comment]
Should be fixed when #465 happens in all mods involved

**Comment by apace100** [comment]
No longer relevant since Origins uses the new Fabric API starting in 1.2.0.
