### ISSUE TITLE
Found Invalid Player Data Fix

### ISSUE THREAD

**Issue by SHXRKIEgg** [apace100/origins-fabric#417]
I tested and found that the Mod Charm is causing Invalid Player Data with Origins. The specific fix is to change the Charm Config "AutomaticRecipeUnlock Enabled" = true to false.

**Comment by SHXRKIEgg** [comment]
Doesn't seem to work anymore still get Invalid Player Data

**Comment by jbjornberg** [comment]
I deleted Outvoted, Charm and Iris- but whenever I add a Datapack it permanently corrupts that world for me. I'm still able to join new worlds, but the moment I add a data-pack- it says "invalid player data".

**Comment by SHXRKIEgg** [comment]
For me its when you make a world and leave and try to rejoin it just says invalid player data no matter what

**Comment by toErIpNid** [comment]
Has this still not been fixed? This seems like a pretty malignant bug.

**Comment by BaronSolace** [comment]
still not fixed

**Comment by apace100** [comment]
I think I have finally tracked down the cause of this bug and managed to fix it. However, due to me not being able to reproduce it with 100% reliability, it may not be fixed in all cases. But I'm optimistic.

The patch will come with the next version, which I hope to release in the coming week.

**Comment by apace100** [comment]
Should be fixed with the newest version (1.1.0, released yesterday)
