### ISSUE TITLE
Better End Elytra and Elytra Trinket not working

### ISSUE THREAD

**Issue by Yannik-T** [apace100/origins-fabric#426]
I can only use the normal elytra in the armor slot but not in the cape slot. And the Elytras from the better end mod don't work completely. That only happens when the origins mod is installed

**Comment by Micalobia** [comment]
This behavior should be fixed by Origins migrating to use https://github.com/FabricMC/fabric/pull/1815 to implement its elytra flight.

**Comment by Micalobia** [comment]
Made a new issue to represent the migration, which can be found here: #465

**Comment by apace100** [comment]
No longer relevant since Origins uses the new Fabric API starting in 1.2.0.
