### ISSUE TITLE
Invalid Player Data On First Load

### ISSUE THREAD

**Issue by ChrisLTheNerd** [apace100/origins-fabric#427]
So when I first join an existing world (mine is from older non-17 game versions) world this mod gives me an Invalid Player Data error then it works ok on the second load. I'm using Origins-1.17-1.0.3, architectury-2.5.27-fabric, fabric-api-0.40.0+1.17, and it's all on fabric loader 0.11.6-1.17.1. Edit: Now it won't let me even do that unless I get a fresh copy of the mod.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/50182206/132780287-fcdca6c2-17dc-45e1-903a-eb98b4213613.gif)

**Comment by SHXRKIEgg** [comment]
I reported this a long time ago and no answer so I doubt it will be fixed soon

**Comment by apace100** [comment]
Should be fixed with the newest version (1.1.0, released yesterday)
