### ISSUE TITLE
Origins destroys Single Player in any modpack

### ISSUE THREAD

**Issue by itsdinkd** [apace100/origins-fabric#432]
As a lot have reported, Origins is corrupting player files in single player worlds. 

Steps to produce:
1. Create a world
2. Exit minecraft
3. Open Minecraft
4. Join world you just created
5. Receive Error "Invalid Player Data"

I've tested this throughout my modpack (200 mods) and origins alone, taking off origins allows me to join back the worlds that once said "invalid player data"

**Comment by Jmac11927** [comment]
Similar issue, but no fix still. I could quit out and rejoin for awhile, but at some point I wasnt able to play at all anymore....

**Comment by apace100** [comment]
Should be fixed with the newest version (1.1.0, released yesterday)
