### ISSUE TITLE
Game crash upon loading latest version (1.1.0)

### ISSUE THREAD

**Issue by ChessMaster2004** [apace100/origins-fabric#436]
At the moment, whenever I load the mod with my launcher, it immediately opens the launcher back up and gives me a crash report... The only other mods i have are OptiFabric and the latest version of OptiFine (I also made sure that Fabric API was up to date, which it was)

**Comment by itsdinkd** [comment]
You know it would help if you showed your crash log right?

**Comment by ChessMaster2004** [comment]
As soon as I get back to my computer I'll let get that to you

-Taylor McLendon

**Comment by apace100** [comment]
Usually when Origins is updated, OptiFabric/OptiFine becomes incompatible. Keep an eye on updates to OptiFabric, as the dev usually tries to make it compatible again.
