### ISSUE TITLE
Crash when using invulnerability

### ISSUE THREAD

**Issue by SnaveSutit** [apace100/origins-fabric#439]
Crash report: [crash-2021-10-13_06.10.15-server.txt](https://github.com/apace100/origins-fabric/files/7337179/crash-2021-10-13_06.10.15-server.txt)
Data Pack: [snavesutit.fishpond.zip](https://github.com/apace100/origins-fabric/files/7337183/snavesutit.fishpond.zip)
Origins version: 1.1.1 for 1.17.1

Caused by using the origins:amount damage condition with the invulnerability power type.

```json
{
  "type": "origins:invulnerability",
  "damage_condition": {
    "type": "origins:amount",
    "comparison": "==",
    "compare_to": 4
  }
}
```

**Comment by apace100** [comment]
The invulnerability power type does not support the amount condition.
If you want to disable damage based on the amount taken, you should use `modify_damage_taken`.
See the wiki page on the invulnerability power:
https://origins.readthedocs.io/en/latest/power_types/invulnerability/
