### ISSUE TITLE
"Climbing" condition only works for vanilla climbing.

### ISSUE THREAD

**Issue by thegatesdev** [apace100/origins-fabric#452]
Add Climbing entity condition, because this:

`
    "condition":{
        "type": "origins:power_active",
        "power": "origins:climbing"
    }
`
does not seem to work

**Comment by eggohito** [comment]
There's already an `origins:climbing` entity condition type. You can check the [wiki](https://origins.readthedocs.io/en/latest/) for more information

**Comment by TheGatesScratch** [comment]
Im sorry, the github wiki does not state a Climbing condition at https://github.com/apace100/origins-fabric/wiki/List-of-entity-conditions . Should I use the origins.readthedocs rather than the github wiki?

**Comment by thegatesdev** [comment]
> There's already an `origins:climbing` entity condition type. You can check the [wiki](https://origins.readthedocs.io/en/latest/) for more information

Im sorry, the github wiki does not state a Climbing condition at https://github.com/apace100/origins-fabric/wiki/List-of-entity-conditions . It seems the github wiki is not updated. thanks.

**Comment by thegatesdev** [comment]
When climbing using this power:
`"type": "origins:climbing",

    "condition": {
      "type": "origins:collided_horizontally"
    },
    "allow_holding": true`
the entity condition "origins:climbing" does not detect it, neither does "origins:power_active" detect if I am using (climbing) it right now.

**Comment by apace100** [comment]
Fixed in Origins 1.3.0
