### ISSUE TITLE
Migrate to use fabric-entity-events-v1 for Elytra flight

### ISSUE THREAD

**Issue by Micalobia** [apace100/origins-fabric#465]
This mod should migrate to use FabricMC/fabric#1815 to implement its elytra flight. This should help with potential incompatibilities with mods like [Better End](https://github.com/paulevsGitch/BetterEnd/issues/362) and [Elytra Trinkets](https://github.com/TheIllusiveC4/CuriousElytra/issues/35).

Would fix #426, #416, #396, #356

**Comment by apace100** [comment]
It already does use that event since version 1.2.0 (the update to MC 1.18).
