### ISSUE TITLE
Crash on grant power action granting elytra flight power

### ISSUE THREAD

**Issue by CatgirlChilis** [apace100/origins-fabric#468]
I can't test if this is present in the 1.18 release yet, so sorry of this is already know/fixed there, but on 1.17.1 / v1.1.4, when I have a power use the origins:grant_power entity action to grant a power that contains an origins:elytra_flight power, (either as it's core or within an origins:multiple) the game crashes, with this error:

The game crashed whilst container click
Error: java.lang.IllegalStateException: Player abilities must be accessed from the logical server (check !world.isClient)
Exit Code: -1

It works as expected if I substitute the flight power for a different one even without changing anything else in the granting power. The flight power works without issue if assigned through commands (or from an origin presumably, as the elytrian origin has no issues that I know of). The revoke power action works fine too.

I attached a smaller version of my datapack with just the conflicting powers in case you want to test this yourself.
[Grant Power Crash test.zip](https://github.com/apace100/origins-fabric/files/7652064/Grant.Power.Crash.test.zip)

**Comment by apace100** [comment]
It shouldn't be present for this power in 1.18 anymore, since the `elytra_flight` power no longer depends on the PlayerAbilityLib dependency.
However, this bug also applies to the `creative_flight` power, even in the 1.18 release, so I'll get that fixed!

**Comment by apace100** [comment]
Fixed in 1.3.0
