### ISSUE TITLE
Damage phasing in and out of blocks

### ISSUE THREAD

**Issue by Kitsu99** [apace100/origins-fabric#483]
Not sure what's causing the issue exactly, as it doesn't happen with other phasing-ability origins. We're using Inkbat's Masked custom origin, and every time we phase into or out of any wood blocks, about a heart of damage is taken. However, the Phantom origin or even Kitsune Custom origin, both of which can also phase through blocks, do not. So i'm not sure if this is an issue with the Masked code exactly, or if there is another issue. Any help would be appreciated

**Comment by Konglomneshued** [comment]
https://github.com/apace100/origins-fabric/issues/473
