### ISSUE TITLE
I take damage in the wall with Phantom Origin

### ISSUE THREAD

**Issue by SomeBirdguy** [apace100/origins-fabric#497]
whenever I pick Phantom origin and go into a solid block, I take damage
![2022-02-06_14 15 37](https://user-images.githubusercontent.com/99142426/152697553-34b60668-39ba-4744-a332-bd367e944e2e.png)

**Comment by eggohito** [comment]
Do you have Lithium installed? If so, please check the pinned issue (https://github.com/apace100/origins-fabric/issues/473)

**Comment by ShadowDeveloper** [comment]
This is an issue with 1.18.1 and the way Minecraft handles collision. If you install Lithium like eggohito mentioned, it's an easy fix
