### ISSUE TITLE
Crash on startup with Minecraft 1.18.2

### ISSUE THREAD

**Issue by Luracasmus** [apace100/origins-fabric#502]
[latest.log](https://github.com/apace100/origins-fabric/files/8180887/latest.log)

The game crashes instantly on startup with Origins and Minecraft 1.18.2.

**Comment by jkingsbury1000** [comment]
Same here....I've installed JAVA 16, Fabric Loader. Fabric API is in the mods folder as is Origin Jar file - can't think what to do next.

**Comment by felixcreate** [comment]
Yeah same here fabric 1.18.2 works fine with all other mods but Origins

https://pastebin.com/bkUa8KyA

**Comment by arichornlover** [comment]
I updated Origins up top with 1.18.2 but heres the catch, the CompileJava is broken

**Comment by apace100** [comment]
Origins has been updated since to support 1.18.2
