### ISSUE TITLE
[REI] Outdated Cloth Config Mod

### ISSUE THREAD

**Issue by GremlinOfChaos** [apace100/origins-fabric#506]
REI is incompatible with any version of cloth config pre-6.2 but origins includes an old version (6.0.42)
(Also i tried adding a new version of cloth config, but the game just crashed without a fabric report, so that's not working)

Full Error:
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Roughly Enough Items' (roughlyenoughitems) 7.3.443 with any version that is compatible with:
Unmet dependency listing:
	 - Mod 'Roughly Enough Items' (roughlyenoughitems) 7.3.443 is incompatible with any version before 6.2- of mod 'Cloth Config v6' (cloth-config), but a matching version is present: 6.0.42!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by arichornlover** [comment]
I have updated the cloth config mod to version 6.2.57
you can find it up top, since I'm not a contributor, I modified some things for the Origins Mod to work on 1.18.2

**Comment by apace100** [comment]
Latest version now uses Cloth Config 6.2.x
