### ISSUE TITLE
Origins 1.3.2-Preview (Unfinished Concept Version)

### ISSUE THREAD

**Issue by arichornlover** [apace100/origins-fabric#508]
[Origins 1.3.2 (Minecraft 1.18.2) sourcecode.zip](https://github.com/apace100/origins-fabric/files/8240847/Origins.1.3.2.Minecraft.1.18.2.sourcecode.zip)
I have created 1.3.2 but there is a problem with the fabric api tags that causes me to not build the .jar
I hope you contributors see this, I mostly updated the mods in the gradle properties and made it support the newer mc version.
-Changes below-
Fabric API 43 is now Fabric API 48
Updated cloth config to 6.2.57 - just in case if something could go wrong
-2 Problems-
:CompileJava not found
Fabric API Modtags

**Comment by apace100** [comment]
Update has been released by now

**Comment by arichornlover** [comment]
I know LOL
I posted this before 1.18.2 support was added, dang it XD
