### ISSUE TITLE
Elytrian Armor Bug 

### ISSUE THREAD

**Issue by TucoErthal** [apace100/origins-fabric#51]
While not wearing any armor, I can equip armor with a protection level equal to or lesser than chainmail. That's intended. But when while wearing light armor, I can switch to heavier armor from the inventory, which doesn't seem right to me.

**Comment by apace100** [comment]
Hey! How exactly are you switching the armor? I couldn't reproduce this bug in my setup, so it might be a compatibility issue with another mod (maybe some mod which modifies the inventory in some way?). It'd be great if you could post a list of your other mods!
