### ISSUE TITLE
Registery Remapping Failed

### ISSUE THREAD

**Issue by PizzaLika** [apace100/origins-fabric#510]
I installed the version the server uses of origin mod and it doesnt work. I even double checked the version the server uses and I use and still doesn't work. Please fix this. Thank You,
![Capture](https://user-images.githubusercontent.com/93825588/159173852-a389fce7-76bb-4cde-abf4-fce2d615d55f.JPG)

**Comment by eggohito** [comment]
Make sure that you have [Mob Origins](https://www.curseforge.com/minecraft/mc-mods/mob-origins) installed in your client
