### ISSUE TITLE
[1.18.2] Crash on startup: Mixin apply for mod origins failed origins.mixins.json:WaterBreathingMixin$UpdateAir

### ISSUE THREAD

**Issue by sean-porras** [apace100/origins-fabric#511]
[latest.log](https://github.com/apace100/origins-fabric/files/8312192/latest.log)
Upon trying to startup, a crash occurs due to origins with Fabric Loader version 0.13.3 on Minecraft 1.18.2

All other mods have been scanned over and searched to be up to date and working with MC v. 1.18.2 and F.L.v. 0.13.3
While I don't believe it could be a mod compatibility issue, it's possible.

The mod worked previously with other mods listed and their MC v. 1.18.2 and F.L.v. 0.13.3 equivalents.

**Comment by felixcreate** [comment]
Origins 1.3.1 doesn't work with Minecraft 1.18.2. There should be a 1.18.2 origins update at some point.

**Comment by NICXx2022** [comment]
what version of fabric do I need to use then?

**Comment by felixcreate** [comment]
Fabric 1.18.1 works with Origins 1.3.1. Just make sure you have 1.18.1 version of fabric api too.
