### ISSUE TITLE
is there a way to change / mod the carnivore power

### ISSUE THREAD

**Issue by KingofMidnight** [apace100/origins-fabric#516]
I need help because I want to change the carnivore power for I can make them eat more food

**Comment by Environmela** [comment]
If I'm not mistaken there's a tag that be modified under a tag that be modified in a datapack.

**Comment by KingofMidnight** [comment]
do u know how because i have never really messed with tags before

**Comment by Environmela** [comment]
I found a page on the Minecraft Wiki on how to make a data pack, https://minecraft.fandom.com/wiki/Data_pack. This is the path to modify what is considered meat here "origins/tags/items/meat" just add whatever items and it should define what is and isn't meat. For more information look at this documentation(it is pretty dense) https://origins.readthedocs.io/en/latest/

**Comment by KingofMidnight** [comment]
i tried it and it didn't work, i put it in a datapack then restarted the server and when i got back in and tested the food it said i still couldn't eat the food still
tbh i just need to know what code to put where

**Comment by KingofMidnight** [comment]
wait nvm i found it

**Comment by parhyriw** [comment]
> wait nvm i found it

I'm trying to do the same thing,  what code did you put in the data pack ?

**Comment by KingofMidnight** [comment]
> > wait nvm i found it
> 
> I'm trying to do the same thing, what code did you put in the data pack ?

if u still need it? text me at King of Midnight#9477
