### ISSUE TITLE
Mark as compatible with 1.18.2

### ISSUE THREAD

**Issue by Ecorous** [apace100/origins-fabric#520]
## Issue:
Latest file on curseforge is not marked as compatible with 1.18.2, while it is compatible with 1.18.2. This causes launchers to not be able to download it on 1.18.2 instances.
## Solution:
Mark file as compatible with 1.18.2 on curseforge
- [x] I have searched the issue tracker to make sure this isn't a duplicate

**Comment by rosalinadev** [comment]
I can't confirm the last file working with 1.18.2, for me it causes the game to crash on startup while applying Mixins.
What versions are you using?

**Comment by Ecorous** [comment]
Oh does it? I thought it worked

**Comment by Ecorous** [comment]
Let me try

**Comment by Ecorous** [comment]
Oh okay it doesn't

**Comment by Ecorous** [comment]
Damn it

**Comment by rosalinadev** [comment]
Too bad, I kinda wanted it to work
oh well.

**Comment by Ecorous** [comment]
same

**Comment by Ecorous** [comment]
It's the WaterBreathingMixin

**Comment by Ecorous** [comment]
Oh, #517 exists

**Comment by Ecorous** [comment]
I got a working 1.18.2 jar!

**Comment by roobscoob** [comment]
> I got a working 1.18.2 jar!

Can you drop a build link? I have a server if you need file hosting: https://fs.hall.ly/

**Comment by Apocalyptapig** [comment]
how the hell? did you build the pull request that's been sitting around for like a week?

**Comment by Remty5** [comment]
It's not very hard to build, you just have to build the dependencies first.
Here's a built jar: https://fs.hall.ly/share-download/7c17a48a-e699-48d5-ae08-e88d11d4387e
How to build: https://paste.ee/p/lmUx2#WiZ38vYPPFiwP4w26O0oBg6PVbS53ajC

**Comment by Ecorous** [comment]
https://fs.hall.ly/share-download/6bbb185f-3b9c-4f38-b248-0cf17a1f5351

**Comment by Ecorous** [comment]
@Apocalyptapig @roobscoob @Remty5

**Comment by roobscoob** [comment]
Thank you!

**Comment by Bipbip2109** [comment]
I built a dispencer here.
