### ISSUE TITLE
Origins causes rejection of clients

### ISSUE THREAD

**Issue by tacogerbil** [apace100/origins-fabric#53]
Been trying to set up a bungeecord/velocity environment and have hit a wall where according to the devs for Velocity and Crossstitch (after looking at the source code) there is a best practice standard proper namespace key and it is not implemented in Origins . This causes Crossstitch to fail at trying to handle the Origins mod..
It rejects with the error
disconnected with: DecoderException : java.lang.IllegalArgumentException: No provider for argument minecraft:layer @ io.netty.handler.codec.MessageToMessageDecoder:98

**Comment by astei** [comment]
#52 will fix this when merged.

**Comment by apace100** [comment]
Fixed, thanks for the PR.
