### ISSUE TITLE
"Failed to load datapacks, can't proceed with server load."

### ISSUE THREAD

**Issue by thecolonel63** [apace100/origins-fabric#551]
When I try to create a server with Origins installed, it crashes as soon as it tries to load the datapack. However I believe the underlying issue is caused by a class change in 1.19, that being the KeyBinding class. In 1.19, the class was probably renamed, causing this issue to appear for me.

I have attached the log file for reference as to the issue I am having.

I know for a fact the issue is not caused by any other mods, as the *only* two mods I have installed are Origins and the Fabric API, both on the latest version for 1.19.

This is a real shame, as some friends and I were looking forward to playing with Origins in a fresh 1.19 world as soon as it was up to date. I understand how difficult it is to maintain mods, especially larger ones like this, and I wish you good luck in fixing the many issues you are encountering after the 1.19 update.

[latest.log](https://github.com/apace100/origins-fabric/files/8855739/latest.log)

**Comment by apace100** [comment]
Thanks for the report, I'll fix this ASAP.

**Comment by apace100** [comment]
Fixed in Origins 1.6.1, sorry for the inconvenience
