### ISSUE TITLE
Error Opening "This server requires you to install Origins mod (v1.4.1) to play"

### ISSUE THREAD

**Issue by koalaloverr** [apace100/origins-fabric#553]
Whenever I try to play on my server I get the error "This server requires you to install Origins mod (v1.4.1) to play"

I have spent the last while setting up a new server on Aternos to play on with several mods. I finally got the last of it set up and went to play and I got this error code. I uninstalled and reinstalled it from Aternos and restarted Minecraft and the server several times. I already have the file for the Origins mod in my Mods Minecraft file on my computer. 

There was also a comment on the CurseForge mods page (where I got this help link from) that complained about the same issue a few hours ago. 

Would be very thankful for any advice or help with this issue. Thank you so much!

**Comment by koalaloverr** [comment]
![image](https://user-images.githubusercontent.com/107335332/173261076-9954a496-29a6-4afd-9a0d-c3a32fb3792b.png)

Well I realized I wasn't playing on the Fabric version which may have caused it but now I'm getting this message? Does this mean I need to download all of the mods to the mods folder or something else?

**Comment by apace100** [comment]
Yes, generally most mods which add any content to your game need to be installed on the server _and_ on the client (the `mods` folder on your local computer). If you don't do that, this error message is what you'll see.

**Comment by DavinDog-glitch** [comment]
What do you mean by not having the "fabric version", and how exactly do you download it on the client because I have it in my mods folder?
