### ISSUE TITLE
Empty Origin's name doesn't work as intended.

### ISSUE THREAD

**Issue by JadeJuno** [apace100/origins-fabric#562]
The "Empty" origin's name and description show up as its Translation Keys (`origin.origins.empty.name` and `origin.origins.empty.description`, respectively).

![image](https://user-images.githubusercontent.com/53577918/174533706-61287888-8b6c-4107-8bdf-60c62f15a3a1.png)

This is because the translation key that the translation files use is `layer.origins.origin.missing_origin.name` and `layer.origins.origin.missing_origin.description`.

**Comment by ChrysanthCow** [comment]
Ignore the above, this is just me porting these changes to the Forge port.
