### ISSUE TITLE
[Feature Request/Idea] New Power Type "Action on Game Event"

### ISSUE THREAD

**Issue by DragonX753** [apace100/origins-fabric#574]
Hello!

I just thought it would be cool if there was a way to make origins with sound-based abilities, using the new 1.19 sound feature.

An idea I had was to have a power type that would activate whenever the player detected a game event. I'm not sure how easy or hard this would be, so it's completely up to you if you want to add it or not.

Some ideas for the power type would be to have a field for the sound strength, a field for a bi-entity action/entity action, or a bi-entity condition/entity condition.

If you do decide to make it, thanks in advance.

**Comment by eggohito** [comment]
This is now in [Origins 1.11.x](https://github.com/apace100/origins-fabric/releases) in the form of a power type named `game_event_listener`
