### ISSUE TITLE
phantom morph key not working

### ISSUE THREAD

**Issue by UltimateOOF** [apace100/origins-fabric#576]
in my friends server, i chose phantom and its key to turn into a phantom wont work, i tried changing the key, i also tested out on a survival world and it works perfectly fine. i think its something up with her server is there something she can do to fix it or anything i can do to fix it?

**Comment by UltimateOOF** [comment]
actually, its not the key, you know the green stuff on the sides of the screen well it turns red, then kicks me out of being in phantom mode, like being a phantom is a timer, then i can turn back til i die.

**Comment by UltimateOOF** [comment]
![2022-07-22_14 41 04](https://user-images.githubusercontent.com/109822028/180503160-f694e074-909f-481b-b7eb-46284bfcc0ae.png)

**Comment by apace100** [comment]
This is intended behaviour. Being in phantom mode drains your hunger. Running out of hunger to the point where you can't sprint anymore means you can't be in phantom mode anymore, meaning once you are down to 3 pips, you'll be kicked out of phantom mode.
The overlay turns red once you're close to that to warn you that you're about to run out.
