### ISSUE TITLE
Specifying a Structure to Spawn in Doesn't Work

### ISSUE THREAD

**Issue by QuantumXenon** [apace100/origins-fabric#587]
Crash Log: https://pastebin.com/kT462Tp1

What I am trying to do:
```
{
    "type": "origins:modify_player_spawn",
    "dimension": "minecraft:overworld",
    "structure": "minecraft:village",
    "spawn_strategy": "default",
}
```

_(Origins 1.6.2, Fabric API 0.58.0, Fabric Loader 0.14.9, Minecraft 1.19)_

**Comment by QuantumXenon** [comment]
I think Tags were changed in Fabric in 1.18.2, so could this potentially be something to do with that? (I see that `structureTag` is null)

**Comment by QuantumXenon** [comment]
I have had an issue where I could not respawn after dying because the spawnpoint was broken by this bug.

**Comment by TheRexYo** [comment]
I have this issue too. I believe it actually has something to do with Villages being split into different structures (eg. "minecraft:village_plains") as opposed to just being "minecraft:village".
