### ISSUE TITLE
Origins mod doesn't detect the client's origins mod on minehut

### ISSUE THREAD

**Issue by leoviczero** [apace100/origins-fabric#590]
When joining a fabric server with origins v1.6.2 on it, it will say I have to install the origins mod to play, even though my mods folder is exactly the same as the server.

**Comment by eggohito** [comment]
Can you provide more information about your server? e.g: the Origins and Minecraft version, whether you're using a proxy or not, the log file of the server, etc.

**Comment by JadeJuno** [comment]
#261
