### ISSUE TITLE
SMP Crashes

### ISSUE THREAD

**Issue by OxiiGiin1** [apace100/origins-fabric#593]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2022-08-28 12:59:36
Description: Ticking entity

java.lang.NoSuchMethodError: 'int net.minecraft.class_2170.method_9249(net.minecraft.class_2168, java.lang.String)'
	at io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$15(EntityActions.java:235)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.ActionOverTimePower.tick(ActionOverTimePower.java:46)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.github.apace100.apoli.component.PowerHolderComponentImpl.serverTick(PowerHolderComponentImpl.java:172)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_3222_1356f9d8.tickServerComponents(Unknown Source)
	at net.minecraft.class_3218.handler$zoi000$tick(class_3218.java:4226)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at io.github.apace100.apoli.power.factory.action.EntityActions.lambda$register$15(EntityActions.java:235)
	at io.github.apace100.apoli.power.factory.action.ActionFactory$Instance.accept(ActionFactory.java:41)
	at io.github.apace100.apoli.power.ActionOverTimePower.tick(ActionOverTimePower.java:46)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at io.github.apace100.apoli.component.PowerHolderComponentImpl.serverTick(PowerHolderComponentImpl.java:172)
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_3222_1356f9d8.tickServerComponents(Unknown Source)
	at net.minecraft.class_3218.handler$zoi000$tick(class_3218.java:4226)
	at net.minecraft.class_3218.method_18762(class_3218.java:712)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 100
	Entity Name: OxiiGiin
	Entity's Exact location: 436.97, 63.00, -1488.79
	Entity's Block location: World: (436,63,-1489), Section: (at 4,15,15 in 27,3,-94; chunk contains blocks 432,-64,-1504 to 447,319,-1489), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,-64,-1536 to 511,319,-1025)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:371)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:339)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['OxiiGiin'/100, l='ServerLevel[Astral City]', x=436.97, y=63.00, z=-1488.79]]
	Chunk stats: 5930
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,142,0), Section: (at 0,14,0 in 0,8,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 57164 game time, 76860 day time
	Level name: Astral City
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 3691 (now: false), thunder time: 112766 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1509971976 bytes (1440 MiB) / 3321888768 bytes (3168 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-10900KF CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2487
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37501.95
	Virtual memory used (MB): 21898.86
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 27.12
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		adventurez: AdventureZ 1.4.15
		alloy_forgery: Alloy Forgery 2.0.15+1.19
		almostunified: AlmostUnified 0.0.4
		antighost: AntiGhost 1.19.1-fabric0.58.5-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19
		anvilrestoration-fabric: Anvil Restoration (Fabric) 1.6
		appleskin: AppleSkin 2.4.1+mc1.19
		attributefix: AttributeFix 17.1.2
		badpackets: Bad Packets 0.2.0
		balm-fabric: Balm 4.5.2+0
		bclib: BCLib 2.1.0
		betterf3: BetterF3 1.3.2
		blossom: Blossom 1.0.5
		blur: Blur (Fabric) 2.6.0
			midnightlib: MidnightLib 0.5.2
			satin: Satin 1.8.0
		bookshelf: Bookshelf 16.1.4
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.2-1.19
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		bountiful: Bountiful 3.0.0
		cardinal-components: Cardinal Components API 5.0.1
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		cleancut: CleanCut 1.19.2-5.1-fabric
		cloth-config: Cloth Config v8 8.0.75
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+11
		collective-fabric: Collective (Fabric) 4.50
			fiber: fiber 0.23.0-2
		controlling: Controlling For Fabric 10.0+6
		craftingtweaks: Crafting Tweaks 15.1.0
		creeperoverhaul: Creeper Overhaul 2.0.3
		croptosis: Croptosis 1.5.1
		ctov: ChoiceTheorem's Overhauled Villages 3.1
		cullleaves: Cull Leaves 2.3.4
		dataattributes: Data Attributes 1.2.7
		diamond_nuggets: Diamond Nuggets 1.3
		doubledoors-fabric: Double Doors (Fabric) 3.7
		dragon: dragon 1.0.0
		dragonfight: Dragonfight Mod 1.19.2-2.6
		dragonloot: DragonLoot 1.1.2
		dramaticdoors: Dramatic Doors (Fabric) 1.19.2-1.3.1
		durabilityviewer: Giselbaers Durability Viewer 1.19.1-fabric0.58.5-1.10.3
			gbfabrictools: GBfabrictools 1.3.4+1.19
		dusk: Dusk Mod 1.19.1-2.2
		easymagic: Easy Magic 4.3.2
		ecologics: Ecologics 2.1.9
		economical_villager_trading: Economical Villager Trading 1.2.8
		edenring: EdenRing 0.6.4
		effective: Effective 1.2.2
		enchdesc: EnchantmentDescriptions 13.0.1
		enderscape: Enderscape 0.3.5-1.19.1
		enhancedcelestials: Enhanced Celestials 2.1.0.1
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		equipmentcompare: Equipment Compare 1.3.1
		everycomp: Every Compat 1.19.2-2.0.4
		expandeddelight: Expanded Delight 0.2.2
		expert_armor: Expert_Armor 2.1.5
		extended_armor_bars: Extended Armor Bars 1.2.1
		fabric-api: Fabric API 0.60.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.11+e62f51a390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.9+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.17+aeb40ebe90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.20+aeb40ebe90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.1+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.11+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.7+0c17ea9690
			fabric-commands-v0: Fabric Commands (v0) 0.2.28+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.34+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.3+aeb40ebe90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.1+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.5+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.8+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.30+aeb40ebe90
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.18+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.28+aeb40ebe90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.28+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.21+aeb40ebe90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.7+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.28+aeb40ebe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.20+aeb40ebe90
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.18+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.2+aeb40ebe90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.3+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.6+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.3+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.14+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.17+aeb40ebe90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.4+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.21+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.11+aeb40ebe90
			fabric-particles-v1: Fabric Particles (v1) 1.0.10+aeb40ebe90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.24+aeb40ebe90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.10+aeb40ebe90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.12+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.20+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.14+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.7+aeb40ebe90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.22+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.16+aeb40ebe90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.11+e62f51a390
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.1+aeb40ebe90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.26+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.13+9ff28f4090
			fabric-textures-v0: Fabric Textures (v0) 1.0.20+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.11+83a8659290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.0+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.3+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.0
		fabricloader: Fabric Loader 0.14.9
		fallingleaves: Falling Leaves 1.12.2+1.19.2
		farmersdelight: Farmer's Delight 1.19-1.3.3
		farmersknives: Farmer's Knives 2.1
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 4.2.3
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		fwaystones: Fabric Waystones 3.0.3+mc1.19.2
			pinlib: PinLib 0.1.3+1.19
		geckolib3: Geckolib 3.1.17
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		gobber2: Gobber2 2.6.36
			pugh_lib: Pugh Lib 1.4.13
			pugh_tools: Pugh Tools 1.3.19
		goblintraders: Goblin Traders 1.5.2
		halfdoors: Half Doors 1.3.9+1.19.x
		harvest_scythes: Harvest Scythes 2.5.3
			mm: Manningham Mills 2.3
		healthoverlay: Health Overlay 7.1.1
		iceberg: Iceberg 1.0.46
		impaled: Impaled 1.1.4
		indium: Indium 1.0.8+mc1.19.2
		indrev: Industrial Revolution 1.15.0-BETA
			fake-player-api: Fake Player API 0.4.0
			libgui: LibGui 6.0.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
			magna: Magna 0.5.2-1.19.1
			noindium: No Indium? 1.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		ingamestats: InGameStats 1.0.9+mc1.19.2
		inmis: Inmis 2.7.0-1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		inventorysorter: Inventory Sorter 1.8.10-1.19
			kyrptconfig: Kyrpt Config 1.4.14-1.19
		iris: Iris 1.2.7
			org_anarres_jcpp: jcpp 1.4.14
		jamlib: JamLib 0.4.4
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.2.0.256
		jeresources: Just Enough Resources 1.1.0.179
		kambrik: Kambrik 4.0-1.19.2
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
			spruceui: SpruceUI 4.0.0+1.19
		legendarytooltips: Legendary Tooltips 1.2.6
		lithium: Lithium 0.8.3
		maxenchantx: Max Enchant X 1.1-1.19.1
		medievalorigins: Medieval Origins 1.19.x-4.1.3
		mermaid: mermaid 1.0.0
		minecraft: Minecraft 1.19.2
		mineralchance-fabric: Mineral Chance (Fabric) 2.1
		mobscarecrow: Mob Scarecrow 2.2.1-1.19.1
		modmenu: Mod Menu 4.0.6
		moonlight: Moonlight 1.19.2-2.0.24
		morevillagers: More Villagers 4.0.2
		mousetweaks: Mouse Tweaks 2.22
		mythicmetals: Mythic Metals 0.15.4
		naturalist: Naturalist 2.1.1
		nears: Nears 1.2.3
		nullscape: Nullscape 1.2
		origins: Origins 1.6.2
			apoli: Apoli 2.5.1
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
				playerabilitylib: Pal 1.6.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		owo: oωo 0.7.3+1.19
		oxidized: Oxidized 1.7.2
		patchouli: Patchouli 1.19.2-76-FABRIC
		pehkui: Pehkui 3.4.1+1.14.4-1.19.2
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		pickupnotifier: Pick Up Notifier 4.2.0
		playerex: PlayerEx 3.3.5
			net_objecthunter_exp4j: exp4j 0.4.8
			opc: Offline Player Cache 0.6.2
			placeholder-api: Placeholder API 2.0.0-beta.7+1.19
		polymorph: Polymorph 0.45.0+1.19.2
		professions: Professions 0.3.5
			com_typesafe_config: config 1.4.1
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			octo-economy-api: Octo Economy API 1.0.1
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		puzzleslib: Puzzles Lib 4.2.4
		regrowth: Regrowth 31.0.0
		rpgdifficulty: Rpg Difficulty 1.2.1
		saplanting: Saplanting 1.1.3+1
		seasons: Fabric Seasons 1.4-BETA+1.19
		skylorlib: SkyLib 1.5.1
		sodium: Sodium 0.4.3+build.17
			org_joml_joml: joml 1.10.4
		spirit: Spirit 2.1.12
		structory: Structory 1.0.1
		supplementaries: Supplementaries 1.19.2-2.0.15
		t_and_t: Towns and Towers - Structure Add-on 1.8.2
		terrablender: TerraBlender 2.0.1.125
		terralith: Terralith 2.3
		thonkutil: ThonkUtil 2.15.4+1.19
			thonkutil-base: ThonkUtil Base 1.13.2+4a8c408a57
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.4.2+3eb2749857
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.1.2+8ff533c957
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.1.2+8ff533c957
			thonkutil-legacy: ThonkUtil Legacy 1.1.2+5d4263f557
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.1.3+bd4b387957
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.5.2+8ff533c957
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.2.2+8ff533c957
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.2.2+8ff533c957
		tipsmod: Tips 8.0.2
		tokenablefurnaces: Tokenable Furnaces 2.0.1
		tooltiprareness: Tooltip Rareness 1.0.6
		trinkets: Trinkets 3.4.0
		tumbleweed: Tumbleweed 0.5.1
		utilitybelt: Utility Belt 1.0.1
		visuality: Visuality 0.5.1
		visualworkbench: Visual Workbench 4.2.0
		vitalize: Vitalize 1.0.0
			resourcefullib: Resourceful Lib 1.1.7
			team_reborn_energy: Energy 2.2.0
		voidz: VoidZ 1.0.9
		wthit: wthit 5.11.3
		wwoo: William Wythers' Overhauled Overworld 3.1.7
		xps: Xp Obelisk 0.4.5.r_for_1.19.x_Fabric
	Loaded Shaderpack: ComplementaryShaders_v4.6.zip
		Profile: HIGH (+0 options changed by user)
	Server Running: true
	Player Count: 1 / 8; [class_3222['OxiiGiin'/100, l='ServerLevel[Astral City]', x=436.97, y=63.00, z=-1488.79]]
	Data Packs: vanilla, Fabric Mods, minecraft/eamodcompat, 1.19_default.zip, Supplementaries Generated Pack, structure_mod_compat.zip, Everycomp Generated Pack, professions/fabric/normal
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.9-1.19.2

**Comment by eggohito** [comment]
Origins is **not** fully compatible with 1.19.x due to changes made to a method on the command system. So, if a power is using either the `origins:execute_command` action types or the `origins:command` entity condition type, it will crash the game.
*(This seems to be the case for your server)*

This will be fixed once https://github.com/apace100/apoli/pull/61 is merged, but for now, stay on 1.19
