### ISSUE TITLE
Unable to connect to origins server through proxy

### ISSUE THREAD

**Issue by bloksskywalker** [apace100/origins-fabric#595]
I have tested with velocity and bungeecord, and it seems the backend server cannot detect the client's version of origins. Every time you try to join you get kicked with "This server requires you to install the Origins mod (v1.7.0) to play." In the console of both Velocity and Bungeecord it just displays this kick message and no other errors. On the server, it displays the username and the kick message with no other errors. (I know it is not a good idea to use proxy behind proxy, and that isn't what I'm doing. I used both at different times to test this error.)

**Comment by bloksskywalker** [comment]
This is also why #590 issue exists as well

**Comment by JadeJuno** [comment]
#261

**Comment by bloksskywalker** [comment]
This worked, thanks!
