### ISSUE TITLE
"type": "origins:modify_attribute" broken???

### ISSUE THREAD

**Issue by Dangomation** [apace100/origins-fabric#606]
I've no idea anymore...
 I've copied  the example from example whole sale from [Modify Attribute](https://origins.readthedocs.io/en/latest/types/power_types/modify_attribute/) example. I've made my own (below) and either I'm missing what a "power" is or somthing is messed up internally. I'm gonna keep at it but dammed is this making me have a headache.

![image](https://user-images.githubusercontent.com/100386195/193915581-4ddc37d3-4706-4cfd-936b-f86c479929c0.png)

## Error Message:
[Render thread/ERROR] (Apoli) There was a problem reading sub-power "origin_practice:health_to_armor_stage_zero" in power file "origin_practice:health_to_armor": Power type "origins:modify_attribute" is not defined.

## Fabric Properties
	minecraft_version = 1.18.2
	yarn_mappings = 1.18.2+build.4
	loader_version = 0.14.9

## Dependencies
	fabric_version = 0.59.0+1.18.2
	origins_version = v1.4.0

**Comment by eggohito** [comment]
The `origins:modify_attribute` power type was added in Origins 1.6.0, which is for Minecraft 1.19

**Comment by Dangomation** [comment]
Oh gotcha. I'm not sure if there are other examples of unexplained version differences in the docs. How come there isn't anything written down in the docs? That really drove me crazy the one day.

**Comment by eggohito** [comment]
There's a version switcher in the wiki located on the bottom right corner of the website
<br>

![image](https://user-images.githubusercontent.com/66972816/195031620-267a2c62-6cc5-48e5-be8c-cfd99def1cb4.png)
