### ISSUE TITLE
All custom-made ' origins:action_over_time ' Powers crash my game

### ISSUE THREAD

**Issue by WillowWLJPearl** [apace100/origins-fabric#608]
After i updated my Origins to 1.7.0 in the depencies of my mod, My game started crashing every time i choose an origin with the 'action over time' power type or more specifically the 'entity action' part of it.
This happened in 1.19.2, and i cant seem to find any difference on using the action over time power type.

Note: Figured it out i was just plain stupid.

**Comment by eggohito** [comment]
Can you provide more information, such as sending the `latest.log` file from your `.minecraft/logs` folder and the crash report file from your `.minecraft/crash-reports` folder?
