### ISSUE TITLE
[Incompatibility] Phantom phasing not working with Lithium installed

### ISSUE THREAD

**Issue by CmdrJane** [apace100/origins-fabric#63]
Simply, if lithium is installed phantoms will be unable to move inside of any type of blocks while in phantom state

Minecraft ver: 1.16.5
Origins ver: 1.16.2/.3/.4/.5: Origins 0.4.6
Lithium ver: lithium-fabric-mc1.16.5-0.6.1
Fabric API: fabric-api-0.29.4+1.16

**Comment by apace100** [comment]
Thanks for the report!
While this isn't fixed on the mod side, you can navigate to the config folder and insert the following line add the end of the `lithium.properties` file:
`mixin.shapes.lazy_shape_context=false`

**Comment by apace100** [comment]
Fixed when using the latest Lithium version (tested with 0.6.3)
