### ISSUE TITLE
Modify Crafting Power Fails On Some Recipes

### ISSUE THREAD

**Issue by OnyxXIII** [apace100/origins-fabric#638]
The [Modify Crafting](https://origins.readthedocs.io/en/latest/types/power_types/modify_crafting/) power fails when used on certain items. When changed to another recipe reference (but without making any other changes), the power works as expected.

A (presumably incomplete) list of recipes the power fails to modify is:

- `minecraft:suspicious_stew`
- `minecraft:firework_star`
- `minecraft:tnt`
- `minecraft:wooden_pickaxe`
- `minecraft:iron_chestplate`
- `minecraft:iron_leggings`
- `minecraft:iron_sword`
- `minecraft:iron_hoe`
- `minecraft:stone_sword`
- `minecraft:diamond_pickaxe`

This failure seems to occur regardless of the method used to select the modified recipe. I have tried it with:

- `"recipe": "minecraft:tnt"`
- `"item_condition": {
        "type": "origins:ingredient",
        "ingredient": {
            "tag": "ntorigins:artisan_tools" //note that this tag contains all tools & armor, and some work and some fail
        }
    }`
- `"item_condition": {
        "type": "origins:is_damageable"
    }`

I haven't tested this, but discord user TheLuxuryShovel#6097 reports that the bug does not appear when using Quilt; only Fabric.

Further discussion on the discord [here](https://discord.com/channels/734127708488859831/1067163088937291856/1067163088937291856), [here](https://discord.com/channels/734127708488859831/734133453544489010/1074439077606199418), and [here](https://discord.com/channels/734127708488859831/734133453544489010/1041214385361797170)

[Here](https://github.com/apace100/origins-fabric/files/10717366/powers.zip) are the 2 powers I tried to build and encountered this bug (sailing the high seas and master artisan) as well as the tag list I used as an attempted workaround when is_damageable didn't work, and here's the [full datapack](https://github.com/apace100/origins-fabric/files/10717362/New.Terrodim.Origins.zip) (with a lot of unrelated origins and powers, some of which are unfinished xD) for testing purposes!

**Comment by OnyxXIII** [comment]
Hey @eggohito just tested this in Origins 1.10.0 / MC 1.20.1, and it's still happening?

Was this fix after that version?
NBD if so, just want to confirm

**Comment by eggohito** [comment]
> Hey @eggohito just tested this in Origins 1.10.0 / MC 1.20.1, and it's still happening?
> 
> Was this fix after that version? NBD if so, just want to confirm

This issue has been fixed in [Origins 1.11.x](https://github.com/apace100/origins-fabric/releases/tag/v1.11.0), which is for Minecraft 1.20.2
