### ISSUE TITLE
"Feather Falling" can't be applied to boots enchanted with "Water Protection" - unlike with every other protection enchantment.

### ISSUE THREAD

**Issue by SpiderKolo** [apace100/origins-fabric#65]
Be it Fire, Blast or Projectile, or just general Protection - all of them can be applied to boots with Feather Falling.
While sure - Feather Falling won't be needed underwater, it makes having an overall traveling outfit protecting from elements much more difficult when you can't combine it with Water Protection for Origins weak to water.

**Comment by apace100** [comment]
Fixed in Origins 0.4.7.
