### ISSUE TITLE
Crashing due to Water Damage - IllegalAccessError

### ISSUE THREAD

**Issue by VexInLimbo** [apace100/origins-fabric#666]
Game crashes when touching water as the Enderian Origin in 1.19.4

It gives the message shown below as an error.
![image_2023-06-07_161851020](https://github.com/apace100/origins-fabric/assets/32753052/eaa78d69-1f7f-42c4-b1a0-b2c1f3c865db)

From what I saw on the full report, the game crashes due to water damage ticks despite me being in Creative. I couldn't find a way to fix it anywhere.

**Comment by apace100** [comment]
Updating your Fabric API fixes this issue. :)

Sorry for any inconvenience this caused!
