### ISSUE TITLE
[Feature] Client Optional? 

### ISSUE THREAD

**Issue by generrosity** [apace100/origins-fabric#676]
Hello!

We are putting together a vanilla+ server, and some users are not interested in interacting with mods at all. Sorry, I checked around and couldn't find out answers to some questions. 

Does origins require the client to have the mod installed or is it optional without server complication? We're putting together our 'optional' mods as part of the shared pack so they can enable only if they want it.

Or, is there a way to defer the race screen until the player triggers a command, or gets a default race that can only be overridden using the mods item?

Thanks for your consideration!

**Comment by apace100** [comment]
Installing the mod on clients isn't optional, I'm afraid. There are many features the mod uses which requires clients to cooperate with the server. Therefore this is not possible, and I'll close this feature request.

However, the second part of your question *is* possible. You can make the mod "auto-choose" the Human origin (no special features at all), which prevents players from choosing an origin at the start. They can then use an Orb of Origin (you'd need to add a crafting recipe or use `/give` to give them one) to get the regular origin selection screen. Another option, not using the item, would be using the `/origin gui <target>` command to make the origin screen appear for them.
To do that, you'd need to use a datapack too, like this one which does what I just described: https://cdn.discordapp.com/attachments/749571272635187342/937741131402313748/Human_Default.zip

Another option would be just using the mod as is. Players who don't want an origin can just choose human in the selection screen.
