### ISSUE TITLE
Apparent incompatibility between Origins (Fabric) and Great Big World Mod

### ISSUE THREAD

**Issue by CaesarSP** [apace100/origins-fabric#678]
So, I've been testing Origins in **Fabric** + a bunch of world-generation mods and, apparently, a mod called **"Great Big World"** seems to crash the game on startup when Origins (Fabric) is enabled in **1.20.1.** 

The crash log: [crash log.txt](https://github.com/apace100/origins-fabric/files/11961337/crash.log.txt)

Dependencies of the Great Big World are Creo Lib, YetAnotherConfigLib and Mod Menu. 
Tell me to delete if it has been posted already.

**Comment by eggohito** [comment]
This looks more like an incompatibility issue with Creo Lib and Reach Entity Attributes, which Origins uses. I suggest posting an issue in their respective repositories
