### ISSUE TITLE
Can't build Origins Fabric v1.7.1 (Minecraft 1.19.2)

### ISSUE THREAD

**Issue by Craprax** [apace100/origins-fabric#679]
I want to add Origins to a mod i am working on and get following message if I want to build the project.

A problem occurred configuring root project 'craftable-orb-of-origin-template-1.19.2'.
> Could not resolve all files for configuration ':modImplementation'.
   > Could not find com.github.apace100:apoli:624eb4d094.
     Searched in the following locations:
       - file:/D:/Gearshift/Development/craftable-orb-of-origin-template-1.19.2/.gradle/loom-cache/remapped_mods/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - file:/C:/Users/denny/.gradle/caches/fabric-loom/minecraftMaven/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - file:/D:/Gearshift/Development/craftable-orb-of-origin-template-1.19.2/.gradle/loom-cache/minecraftMaven/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - https://maven.fabricmc.net/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - https://libraries.minecraft.net/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - https://libraries.minecraft.net/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.jar
       - https://repo.maven.apache.org/maven2/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - https://ladysnake.jfrog.io/artifactory/mods/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - https://jitpack.io/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - https://maven.shedaniel.me/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
       - https://maven.terraformersmc.com/com/github/apace100/apoli/624eb4d094/apoli-624eb4d094.pom
     Required by:
         project : > com.github.apace100:origins-fabric:v1.7.1

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

I've tried forking v1.7.1 and changing the version of apoli but i'll get other dependecy problems with calio.

Cheers 
Craprax

**Comment by eggohito** [comment]
Try using my fork, which you can do so by using `com.github.eggohito:origins-fabric:1.7.1` in the `dependencies` block of your `build.gradle` file
