### ISSUE TITLE
Diverge away from JitPack

### ISSUE THREAD

**Issue by ChrysanthCow** [apace100/origins-fabric#682]
Hi, I'm writing this so you can consider moving away from JitPack for your developer builds.

## Why should we see this change?
JitPack is unreliable, basically every build that has happened over 1.19.x and 1.20.x has failed in some way, shape or form. It'd be far more ideal if you were to upload to a custom maven that developers may use in their projects.

## What are the benefits to a custom maven?
Well, you'd be able to control your own builds a lot more nicely. Such as being able to push while certain dependencies (see Reach Entity Attributes) have not gotten a proper version of their own. It also has more permanence than JitPack, so if a build works, it'll work forever

## Cool! How do I manage this?
You'll need to make a custom block within your build.gradle to support this, then you'd run a gradle command to publish the artefacts. Cool, should be easy enough.

## What happens to JitPack?
I'd keep it as a backup for builds to be published to. It's there just in case the maven goes down or fails in some way.

# Hosts
maven.merchantpug.net
- I personally wouldn't go with this one. The main origins community would probably complain upon seeing my name associated with the mod while ignoring any context besides this, you're better off with somebody more liked or neutral standing in the community.

**Comment by ChrysanthCow** [comment]
If you're an addon dev/former addon dev that has thoughts, please comment down below. Let your voices be heard.

**Comment by ChrysanthCow** [comment]
I'd also happily weigh up the viable options of potential maven hosts, so volunteers to host the project are appreciated.

**Comment by apace100** [comment]
Hi!

I completely agree with you that JitPack - while convenient - is a bit of a nuisance. My biggest gripe with it is the lack of SemVer support. I'd love to include the MC version in my mod's version while respecting SemVer (like `1.0.0+mc1.20.1`, which JitPack can't handle (they don't support `+`).

Regarding the other issues - I'd like to point out that both CurseForge and Modrinth provide Maven repositories to retrieve mods that have been released on their sites! I should probably add that information in the README of my mods.

But, seeing as I do see the benefits, I have started contacting a possible Maven host. :) We'll see how it goes!

**Comment by ChrysanthCow** [comment]
Apoli and Calio not being on CurseForge/Modrinth is what kills CurseMaven and Modrinth Maven as options for this mod.

But, it's good to hear that you're open to having the mod hosted through a maven.

**Comment by apace100** [comment]
Really? I thought depending on Origins would include the binary of it,
meaning it'd include the included libraries as well.
I suppose they aren't referrable in your add-on's code then?

**Comment by ChrysanthCow** [comment]
I'd have to check, but in use cases where you don't want origins but instead want Apoli/Calio, it's not super helpful.

A maven is definitely the way to go for those two.

**Comment by SzczurekYT** [comment]
Was this done? I can't find any mention of non jitpack repo, and jitpack broke again, which is as other said very annoying.
If not please reconsider putting apolio calio on modrinth so we can use modrinth maven, or using something like https://codemc.io

**Comment by eggohito** [comment]
Yes, this has been done for quite some time. Calio/Apoli/Origins has migrated to Ladysnake maven. You can read more on how to migrate to using that maven in your projects here: https://gist.github.com/eggohito/b5c5ae541b75feec6cb5ad15f0383be8

**Comment by SzczurekYT** [comment]
> Yes, this has been done for quite some time. Calio/Apoli/Origins has migrated to Ladysnake maven. You can read more on how to migrate to using that maven in your projects here: https://gist.github.com/eggohito/b5c5ae541b75feec6cb5ad15f0383be8

Awesome, this should be documented on the wiki.

But I still need the ton of other repos, that's how it works in java right?
