### ISSUE TITLE
Elytra textures missing

### ISSUE THREAD

**Issue by FallenX-0** [apace100/origins-fabric#684]
Im not sure why but the elytra textures are missing. Normal elytra textures are fine. Im playing with a modpack but idk what would have caused this.

**Comment by eggohito** [comment]
If you mean elytra textures used by powers that use the `elytra_flight` power type, then it's likely that the client doesn't have the asset(s) loaded. The custom elytra textures have to be put in a resourcepack and be enabled in order to be loaded, otherwise, it will be just a missing texture

**Comment by FallenX-0** [comment]
ah, ok, thank you. how would i do that? its not just on my client, but for everyone in the server its missing textures as well.

**Comment by eggohito** [comment]
Very late reply, but you can follow the steps presented in [this tutorial](https://www.youtube.com/watch?v=qCVPgn3IppU&pp=ygUebWluZWNyYWZ0IHNlcnZlciByZXNvdXJjZSBwYWNr) to setup a server resource pack
