### ISSUE TITLE
Somehow incompatible with Vulkan Mod

### ISSUE THREAD

**Issue by enaemulon** [apace100/origins-fabric#686]
Exactly what the title says, tried testing it together with the Vulkan renderer mod and the game simply wouldn't boot up

**Comment by eggohito** [comment]
As [the notes in the GitHub repository for the Vulkan mod says:](https://github.com/xCollateral/VulkanMod#notes)
> If you come across any mod that do not work with this mod, please create an issue inside **this** (referring to the Vulkan mod's) repo and **do not** report it to the mod developer.
