### ISSUE TITLE
Swapping Origins causing immortality Glitch

### ISSUE THREAD

**Issue by Zunwolf1896** [apace100/origins-fabric#690]
We are currently doign testing to open up a 1.20.1 sevrer. Using Fabric, Origins, Pehkui and around 150 other mods. 

We are currently testing Origins, including datapack ones. Everythign is workign fine until we change origin (using the /origin gui command) around 5+ times then that person and anyone new who joins the server is immortal. They can not take damage or die, but can still hurt others. 

Restarting the entire server fixes this temporarily until it starts up again. There are no errors in the console or logs, we can't figure out what is causing it, We suspect it might be somethgin to do with swapping origins who have different health?

**Comment by LinkusDinkus** [comment]
The same thing happened to me before, I tested for a while and I figured out that an origin addon mod caused it, I deleted all four of my origin addon mods which were, Touhou origins, mob origins, origin tweaks, and extra origins.

**Comment by eggohito** [comment]
Hello! Can you test if this is still the case in [Origins 1.11.2](https://github.com/apace100/origins-fabric/releases/tag/v1.11.2)? The way the selection invulnerability works has been changed and might've fixed this issue

**Comment by Zunwolf1896** [comment]
Thats for 1.20.2 and we are on 1.20.1, we are not planning on updating to .2

**Comment by eggohito** [comment]
I'll be closing this issue since the issue reported should be fixed in Origins 1.11.x or above with how the selection invulnerability has been changed. If this is still happening in those versions, feel free to let me know and I'll re-open this issue

We (currently, but that's mostly just me) have no plans on backporting features to older versions
