### ISSUE TITLE
It says invalid player data when I make a world.

### ISSUE THREAD

**Issue by reaper56310** [apace100/origins-fabric#695]
When I make a world it always says "connection lost invalid player data"
the mods I have include:
Acclaimed Origins, Air Chidori Origin - Origins Addon, Aqua Chidori Origin - Origins Addon, Cloth Config API (Fabric/Forge)                Consulars' Origins, Dark Chidori Origin - Origins Addon, End Origins, Extra Origins, Fabric API, Land Chidori Origin - Origins Addon, Magic Origins, Mob Origins, Origins (Fabric), Origins Extra Keybinds, Origins++, Pehkui, Proman's Origins, Sculker [Origin]           TooManyOrigins
Witherborn Origins

Please find a fix

**Comment by reaper56310** [comment]
all of them are for update 1.20.1

**Comment by eggohito** [comment]
Can you send the *entire* output log? "Invalid player data" can be caused by a few factors, and the output log should give a hint on what's causing the issue. Also, make sure to check https://github.com/apace100/origins-fabric/issues/548 as well, in case that might fix your issue
