### ISSUE TITLE
A small suggestion: lava swimming and underlava visibility

### ISSUE THREAD

**Issue by linzexin022** [apace100/origins-fabric#7]
Hi there, after playing Origins mod for few days, I have an idea in my mind: Since Blazeborn are immune to fire damage, how do you think of giving them the ability to swim at a high speed in lava as Merling swim fast in water? Merling can see underwater, thus Blazeborn can see underlava, while they can only hold their breath for a limited time in lava. These two races are just in contrast! 
Of course, other races can do the same thing in lava but they have to pay some price for that. For example, there is a mod called "Torrid Vision" which adds the _**Torrid Vision Potion**_ that gives the ability to see 20 blocks under lava. Other races should drink _**Torrid Vision Potion**_ and **_Fire Resistance Potion_** to jump into lava.

It's fine if you don't think so :).

**Comment by linzexin022** [comment]
By the way! I found an interesting mod call Trap Expansion, in which there's a block called slippery stone that prevents spiders from climbing. Do you know how to stop Arachnid from climbing such blocks? Add a tag or something else? I have been studying how to make a fun modpack to play with friends, but my lack of knowledge of coding limits my hands-on ability... It would be great if you can give me some advice!

**Comment by apace100** [comment]
Swimming in lava like in water has been suggested before! I'm thinking about adding those powers, because they sound really cool, but I don't think I'll add it to the Blazeborn (at least not by default, you could of course use a data pack to add those)!

If I get these implemented, there's a chance that there will be a second fire-themed origin. :)

I opened a separate issue for your second comment.

**Comment by linzexin022** [comment]
Thank you! I will try making a datapack by myself!

**Comment by apace100** [comment]
Data packs now allow these. In fact, I even published an example data pack with a "Salamander" origin - which allows lava swimming and has better lava visibility. You can find the pack on my Discord server (link is on the CurseForge page) and in this repository: https://github.com/apace100/origins-example-packs
