### ISSUE TITLE
origins:modify_air_speed does not seem to be working

### ISSUE THREAD

**Issue by BleachKing919** [apace100/origins-fabric#703]
While origins:modify_air_speed is able to make entities go faster, I cannot get it to make entities slower than normal while flying, falling, or doing really anything in the air.

**Comment by eggohito** [comment]
Can you provide more information? Such as: which version of Origins are you using? Anything in the output logs? (sending the output logs would be preferred)

**Comment by eggohito** [comment]
Closing this issue, since OP seems to be using the unofficial Forge port of Origins
