### ISSUE TITLE
suffocation

### ISSUE THREAD

**Issue by PlatinumMicah** [apace100/origins-fabric#706]
hii, so i have the origins mod installed and i suffocate with the phantom origin but i dont have lithium installed at all and i cant find anything else that has been documented that causes this outside of lithium

what do i do?

**Comment by eggohito** [comment]
If you're playing on a server, then the server might have Lithium installed. Also, you'll have to provide more information, because as it is at the moment, it's pretty vague. Can you send your output log (the `latest.log` file from your `.minecraft/logs` folder)?
