### ISSUE TITLE
Conditioned Attribute not using set condition

### ISSUE THREAD

**Issue by Kelsege** [apace100/origins-fabric#707]
In an addon I'm working on, I have two functions that use conditioned_attribute, one activating when using a power, and another when on fire. These functions worked in an older build on 1.19, however they now seem to ignore the set condition, and instead activate upon spawning, then deactivates shortly after. Interestingly, setting a tick_rate seems to prevent them activating on spawn, though they still don't activate with the set condition. I have tested this in both Quilt and Fabric, and the issue occurs in both. It is also possible I'm just stupid, but nevertheless, I can't get these to work.

**Comment by eggohito** [comment]
This is a known issue, which has been fixed as of https://github.com/apace100/apoli/commit/b94337c17d1f8d15bc237877d64f0dee9d0d4ffd (meaning it should be fixed in the next update)
