### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by Cinna457** [apace100/origins-fabric#708]
Em um servidor, meus amigos e eu estamos testando todas as origens e percebemos depois de tentar Fea/Pixie que, usando a habilidade de origem nas outras origens, sempre levitaríamos

**Comment by eggohito** [comment]
> On one server, my friends and I are testing all the origins and we realized after trying Fea/Pixie that, using the origin skill on the other origins, we would always levitate

This doesn't really seem like an issue with the origins **provided by the Origins** mod, but more like an issue with the data pack/mod that adds the Fea/Pixie origin that you're mentioning. Make sure to report this to the author of that data pack/addon

*Translated via DeepL:*
> Isto não parece ser um problema com as origens **fornecidas pelo mod Origins**, mas sim um problema com o pacote de dados/mod que adiciona a origem Fea/Pixie que estás a mencionar. Certifica-te de que comunicas isto ao autor desse pacote de dados/addon
