### ISSUE TITLE
Incompalibility

### ISSUE THREAD

**Issue by Someporson** [apace100/origins-fabric#71]
When i use forge of 1.16 or higher every time i load the mod it says it is a fabric mod and does not load the mod is there a way to fix this?

**Comment by V-Celestial** [comment]
Fabric and Forge are 2 different modloaders.
forge mods can't be played on fabric and vice versa.
and since origins is a fabric mod, it can't be played on forge.

**Comment by apace100** [comment]
What V-Celestial said.
