### ISSUE TITLE
Inchling view height too low

### ISSUE THREAD

**Issue by hurtz2p** [apace100/origins-fabric#719]
encountered on ver. 1.19.2 - 1.7.1
Player height as an inchling is 0.5 blocks tall, but first person view height is closer to 0.125 blocks tall.
As a result, player cannot see anything when walking on blocks such as snow.

**Comment by eggohito** [comment]
Inchling is added by the Extra Origins addon, so if you're having issues with it, please report it in Extra Origins' issue tracker: https://github.com/MoriyaShiine/extra-origins/issues
