### ISSUE TITLE
Take damage in wall with the Phantom Origin using Lithium mod

### ISSUE THREAD

**Issue by Terrafin72** [apace100/origins-fabric#721]
You take damage while you are in wall with the Phantom Origin using the Lithium mod.

I'm using Fabric 1.19.2
The mod version is 1.7.1

**Comment by eggohito** [comment]
This is an incompatibility with one of Lithium's optimization rules. You can follow the steps described in https://github.com/apace100/origins-fabric/issues/473#issuecomment-997403061 to solve the issue
