### ISSUE TITLE
Origins causes crash [1.20.1, Fabric]

### ISSUE THREAD

**Issue by jukarr** [apace100/origins-fabric#729]
Origins is preventing the game from starting on 1.20.1 at all. The latest log doesn't mention it specifically, but whenever I remove it the game starts without issue. While installed, even without any add-ons, it says a wide variety of mods as the reason: first it was Epic Knights, then Snowy Spirit, etc.

[latest.log](https://github.com/apace100/origins-fabric/files/14385634/latest.log)
[crash-2024-02-23_14.28.56-client.txt](https://github.com/apace100/origins-fabric/files/14385680/crash-2024-02-23_14.28.56-client.txt)

**Comment by eggohito** [comment]
This seems to be caused by an incompatibility with the Elytra Physics mod. Try removing that and see if it still crashes

**Comment by jukarr** [comment]
That actually fixed it, thank you!
