### ISSUE TITLE
How do I get a player to choose another origin?

### ISSUE THREAD

**Issue by seriousfreezing** [apace100/origins-fabric#734]
I've already deleted the player's player data and nothing has been done about the mod, how do I change the player's origin? Or make this player do it?

**Comment by ChrysanthCow** [comment]
You could always use the `/origin gui` command when both of you are online.

**Comment by seriousfreezing** [comment]
Will the user need permission to use this command as well or not?

**Comment by ChrysanthCow** [comment]
The user won't require any permission for this to work, only the person running the command will.
