### ISSUE TITLE
confused

### ISSUE THREAD

**Issue by YTVirgo** [apace100/origins-fabric#74]
I don't know how to use it on my server can you help me out with setting it up I couldn't find any tutorials

**Comment by apace100** [comment]
Just google "Setting up a Fabric Minecraft server" and follow that general tutorial. Then all that's left to install Origins is dropping the Origins mod file into the mods folder of your server.

And don't forget to install Origins for your client as well. If the mod doesn't work in singleplayer, it won't work when you try to play on a server.
