### ISSUE TITLE
Issue with wrapping badges in origin screens

### ISSUE THREAD

**Issue by Reniel80** [apace100/origins-fabric#741]
![recipes](https://github.com/apace100/origins-fabric/assets/98614051/997ee701-a3d9-4b31-8087-9d7ade2624d3)
1.20.2: Origins 1.12.6

**Comment by eggohito** [comment]
Pain and suffering :pensive: I really should do more intensive tests. Thanks for the heads up!

**Comment by eggohito** [comment]
Would you be able to send the data pack?
