### ISSUE TITLE
Active Power (Secondary) has no default binding

### ISSUE THREAD

**Issue by hakanai** [apace100/origins-fabric#748]
Active Power (Secondary) currently has no binding.

Additionally, while trying to assign the binding, I got what looks like an untranslated string, but I'm not sure how.

![image](https://github.com/apace100/origins-fabric/assets/43236/56b60440-aa67-450f-a52f-c1ad472192e7)

## Reproduction Steps

- Start game
- Options...
- Controls...
- Key Binds...
- Scroll down to find Active Power (Secondary)\
- Observe: Key binding has not been set
- Press keys: <kbd>compose</kbd><kbd>g</kbd><kbd>g</kbd>
- Result is screenshot above.

The quirk of showing "scancode.0" may be a bug in Minecraft itself, but the only issue I'm reporting here is that the binding should probably be set to _something_ so that I don't have to come in here to do it.

**Comment by eggohito** [comment]
The secondary active keybinding is unused and unbound by default (it's not used by any of the base origins.) Its only purpose is to provide an additional keybinding for users to use when making their own origin data packs. The said "scancode.0" quirk might be an issue with MacOS (or *nix systems)
