### ISSUE TITLE
"condition" key should be reserved for Multiple power type

### ISSUE THREAD

**Issue by CammiePone** [apace100/origins-fabric#752]
just a suggestion as it would result in much cleaner jsons, but the "condition" key should probably be one of the few reserved keys for the Multiple power type, just like the "hidden" and "type" keys are

and if it is already, it may be worth updating the docs
https://origins.readthedocs.io/en/latest/types/power_types/multiple/

**Comment by eggohito** [comment]
The `condition` (and many other) key(s) is actually already reserved for a long time. Just need to update the docs, whoops
