### ISSUE TITLE
Crash on Minecraft 1.20.1 using `origins:status_bar_texture`

### ISSUE THREAD

**Issue by PoolloverNathan** [apace100/origins-fabric#762]
# [Crash report](https://mclo.gs/t6nez2P)

When making a simple power using the `origins:status_bar_texture` power type, any player with the power will crash immediately, making worlds unplayable. The following simple power triggers this:

```json
{
	"type": "origins:status_bar_texture",
	"texture_map": {
		"minecraft:hud/food_empty": "minecraft:hud/food_empty"
	}
}
```

**Comment by JadeJuno** [comment]
Could you send the crash report?

**Comment by AphoticGoblin** [comment]
This is because you are using 1.20.1 but with a feature (texture maps) that is only available past it. 
![image](https://github.com/user-attachments/assets/fb26df7b-de74-401a-8e0e-6a4d0cf8e94b)
Switch versions on the wiki by clicking on the button in the corner to avoid this in the future

**Comment by PoolloverNathan** [comment]
Oh, thanks! I'll backport it, I guess.
