### ISSUE TITLE
[1.21] World Corruption? Idk what to call it

### ISSUE THREAD

**Issue by Shadowpudding** [apace100/origins-fabric#767]
I ran into a strange issue with the mod, after choosing an origin (Shulk in my case) and trying to reenter a world it won't load the world and get stuck on the loading screen or kick me to the server selection. At the same time the log in the curseforge app freaks out and gives me a server log. The world won't show up in the world selection screen until i restart the game and the screen background turns black. Disabeling the mod allows me to load into the world again without issues.

I do currently use the skip launcher function of curseforge because microsoft broke them for me.

The logs:
[crash-2024-07-26_18.15.53-server.txt](https://github.com/user-attachments/files/16395322/crash-2024-07-26_18.15.53-server.txt)
[crash-2024-07-26_18.18.16-server.txt](https://github.com/user-attachments/files/16395324/crash-2024-07-26_18.18.16-server.txt)
[crash-2024-07-26_18.24.43-server.txt](https://github.com/user-attachments/files/16395325/crash-2024-07-26_18.24.43-server.txt)

**Comment by eggohito** [comment]
Try removing Origins and see if the issue still persists. Looking at the crash report, it doesn't seem like Origins is the one causing the crash at all, but it could be an incompatibility 🤔

**Comment by Shadowpudding** [comment]
As written in my report the world loads up perfectly fine after disabeling Origins. Since the crash reports dont indicate which mods might be causing the issues i have no idea where to start with disabeling other mods to test for any incompatabilities

**Comment by eggohito** [comment]
The first and second crash report seems to be caused by Villager Names and the third crash report seems to be caused by Biolith. It's strange that these issues only occur when Origins is installed, even though the crash report don't have anything else related to Origins at all 🤔

**Comment by Shadowpudding** [comment]
The issue seems to be fixed with the most recent update. I asume it was the same issue as #764
