### ISSUE TITLE
Respawn getting reset to world spawn after death when using Terralith

### ISSUE THREAD

**Issue by Karminit** [apace100/origins-fabric#768]
When setting respawn point using bed it resets to world spawn after death if both Origins and Terralith mod installed
![respawn point not saving](https://github.com/user-attachments/assets/0995fb99-5f09-4449-bf2d-605d388a0905)

**Comment by BenMillion1** [comment]
This exact problem also happens to me too but I only have origins installed.

**Comment by eggohito** [comment]
This will be fixed in 1.13.0-alpha.6 👍
