### ISSUE TITLE
Avian Speed Buff Negated

### ISSUE THREAD

**Issue by higgy999** [apace100/origins-fabric#77]
Because of the slow falling effect, sprint jumping is slower then actually running. A feature that I would like to see is crouching in mid air will trigger the effect instead of always being enabled. That fixes the issue and allows for the class to have more control over it's effects as lack of meat in early game is devastating. Avian right now is a lesser Elytrian. Every other class has some base control over it's effects.

**Comment by apace100** [comment]
This has been improved in Origins 1.1.0, where Avians received a "Like Air" power, making their speed modifiers also apply while in air.
