### ISSUE TITLE
Could not execute entrypoint stage 'client' due to errors, provided by 'origins'!

### ISSUE THREAD

**Issue by TH4N4702** [apace100/origins-fabric#78]
[crash-2021-02-13_18.42.15-client.txt](https://github.com/apace100/origins-fabric/files/5976192/crash-2021-02-13_18.42.15-client.txt)
 here's the crash report, i dont understand what happened because it was working perfectly yesterday... if someone could help me it would be awesome !
also here's some infos :
Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 875237552 bytes (834 MB) / 1342177280 bytes (1280 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 2
fabric api version - fabric-api-0.30.0+1.16
origin mod version - 1.16.4-0.4.6

news-  "The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14"
- "Process crashed with exit code -1"

**Comment by ElementalKitty** [comment]
Have you tried deleting literally everything in config? Cause that’s what fixed it for me.

**Comment by apace100** [comment]
Yep. Not completely sure what causes this yet, but it can be fixed by deleting the `origins.toml` file which you can find in `.minecraft/config` and then starting up Minecraft again.
