### ISSUE TITLE
Cannot create items that set specific origins in alpha.9

### ISSUE THREAD

**Issue by StvnC12** [apace100/origins-fabric#783]
In 1.13.0-alpha.8
I run command 
`/give @s minecraft:stick[origins:origin=[{origin: "origins:shulk", layer: "origins:origin"}]]`
![image_2024-10-20_225945807](https://github.com/user-attachments/assets/299f24c9-5d69-4f3a-980c-8ceec3d770ea)
this works in changing my origin to shulk

In 1.13.0-alpha.9
I run command
`/give @s minecraft:stick[origins:origin=[{origin: "origins:shulk", layer: "origins:origin"}]]`
![image](https://github.com/user-attachments/assets/1e920ccc-faf7-4d6d-9640-381965b02f92)
this opens the choose origin GUI

**Comment by eggohito** [comment]
This should now be fixed in [1.13.0-alpha.11](https://www.curseforge.com/minecraft/mc-mods/origins/files/6001699)
