### ISSUE TITLE
Question, need a way to reduce fall damage without disabling it completely

### ISSUE THREAD

**Issue by DaytonaBlep** [apace100/origins-fabric#787]
I have a question regarding creating custom powers. I'm trying to create a power that will reduce fall damage and increase safe fall distance, but I couldn't do any of that, the logs say something like: 
`Identifier "minecraft:fall_damage_multiplier" was not registered in registry "minecraft:attribute"`
In general, I'm not sure if I'm writing this name correctly or if the attribute may not be compatible with the player at all. I doubt it's even possible anymore. Has anyone encountered similar problems, and found a solution? Are there any workarounds?
Also i'm on 1.20.1

**Comment by eggohito** [comment]
You can use the [`origins:modify_damage_taken` power type](https://origins.readthedocs.io/en/1.10.0/types/power_types/modify_damage_taken/) and use the [`origins:from_falling` damage condition type](https://origins.readthedocs.io/en/1.10.0/types/damage_condition_types/from_falling/) in its `damage_condition` field to modify the damage taken from fall damage.

**Comment by DaytonaBlep** [comment]
> You can use the [`origins:modify_damage_taken` power type](https://origins.readthedocs.io/en/1.10.0/types/power_types/modify_damage_taken/) and use the [`origins:from_falling` damage condition type](https://origins.readthedocs.io/en/1.10.0/types/damage_condition_types/from_falling/) in its `damage_condition` field to modify the damage taken from fall damage.

This is brilliant! I have to try it

**Comment by DaytonaBlep** [comment]
I also experience problems using [origins:set_fall_distance](https://origins.readthedocs.io/en/latest/types/entity_action_types/set_fall_distance/), I want, in addition to decreasing fall damage, to increase the safe fall distance. I don’t understand what to use it to passively change the safe fall distance. I get errors of incorrect or absent power type.

**Comment by DaytonaBlep** [comment]
Everything said above worked to partially reduce damage taken, but I decided to use "origin:in_tag" and "minecraft:is_fall" as damage condition.
