### ISSUE TITLE
Difficulty using "origins:in_thunderstorm", error loading custom power

### ISSUE THREAD

**Issue by DaytonaBlep** [apace100/origins-fabric#789]
I'm trying to use "origins:in_thunderstorm" to make the character vulnerable to thunderstorm fear, making damage dealt less while the player is outdoors during a thunderstorm, and adding "origins:shaking" for aesthetic completeness.

But I have repeatedly encountered the problem of not loading power, the log says: `Unknown registry key: origins:in_thunderstorm`

**Comment by eggohito** [comment]
Can you send your entire output log? I'm going to need more information to work with 🤔

**Comment by DaytonaBlep** [comment]
[latest.log](https://github.com/user-attachments/files/17639548/latest.log)

**Comment by eggohito** [comment]
The `in_thunderstorm` entity condition type was introduced in Origins 1.11.0, which is for Minecraft 1.20.2. You can achieve a similar thing by using the [`origins:predicate` entity condition type](https://origins.readthedocs.io/en/1.10.0/types/entity_condition_types/predicate/) with [a predicate](https://minecraft.wiki/w/Predicate) that uses the `minecraft:weather_check` type
