### ISSUE TITLE
"Connection Lost: Invalid player data" on a new world with no additional origins

### ISSUE THREAD

**Issue by PencilVoid** [apace100/origins-fabric#791]
Minecraft version: 1.21.1
Fabric version: 0.16.9
Fabric API version: 0.108.0
Origins version: 1.13.0-alpha9
[Log](https://mclo.gs/PO0x8WU)

The only mod installed related to Origins is Origins itself. No datapacks were added to the world, aside from the base Minecraft and Fabric datapacks.

**Comment by eggohito** [comment]
This is related to https://github.com/apace100/origins-fabric/issues/781

**Comment by PencilVoid** [comment]
After some testing, the issue seems to be caused by the Splinecart mod being present.
