### ISSUE TITLE
According to wiki, spawn action has a bientity_action field, but in fact it is not implemented at 1.20.1

### ISSUE THREAD

**Issue by Karashok-Leo** [apace100/origins-fabric#792]
I think it would be better to annotate the applicable versions of each entry on the wiki, or port these features back to old versions.

**Comment by eggohito** [comment]
You can click the black box at the bottom-right corner of the wiki to change its version (by default, it's set to "latest", which refers to the latest version of Origins (currently 1.12.x, alpha versions are currently not documented in the wiki))
![image](https://github.com/user-attachments/assets/f88da025-3b44-4fad-973e-97b2a572fb88)
![image](https://github.com/user-attachments/assets/33deda4a-0c69-40c1-bad9-58e40e6f9c21)
