### ISSUE TITLE
[1.21.1 alpha9] Origin Layers do not register Origins (When trying to replace)

### ISSUE THREAD

**Issue by GekidoLukas** [apace100/origins-fabric#793]
So, I updated to the latest alpha, but my origins were not showing up anymore. 

I used another datapack to load origins, but it did not work. The origins themselves seem to exist, because they are registered. Just not in that specific layer:
![image](https://github.com/user-attachments/assets/0609db3a-f0cf-4c7b-8123-f528309a92ca)

I double checked my syntax on the discord server and it seems to be all correct

**Comment by GekidoLukas** [comment]
Okay, it only works, when I don't try to replace

**Comment by eggohito** [comment]
Issue was resolved in Discord (see: https://discord.com/channels/734127708488859831/1307593020241088582/1307593020241088582)
