### ISSUE TITLE
Reselecting an origin crashes the game

### ISSUE THREAD

**Issue by XoToM** [apace100/origins-fabric#80]
[crash-2021-02-13_21.08.12-client.txt](https://github.com/apace100/origins-fabric/files/5976545/crash-2021-02-13_21.08.12-client.txt)
[crash-2021-02-13_21.15.17-client.txt](https://github.com/apace100/origins-fabric/files/5976546/crash-2021-02-13_21.15.17-client.txt)

If you use the orb of origins to select an already selected origin the game crashes.
The crash only happens if you use the orb at least twice. without leaving the world.

**Comment by apace100** [comment]
Fixed in 0.4.7.
