### ISSUE TITLE
Enderian not having the reach if not OP.

### ISSUE THREAD

**Issue by justreathy** [apace100/origins-fabric#90]
Hey, as I own server, with Origins mod, there are some players. One of my players told me, he doesnt have his reach. I tried it, and discovered that Enderian doesn't have the reach when not OP. Is there a way to fix it?

**Comment by apace100** [comment]
I couldn't reproduce this issue. Do you maybe have some other mods on your server (some form of anti-cheat mod maybe?) which could prevent their reach from being increased?
Either way, for extending the reach, Origins relies on a third-party library mod called Reach Entity Attributes. If you still have this problem, please post an issue [on their issue tracker](https://github.com/JamiesWhiteShirt/reach-entity-attributes/issues). Feel free to link back to this issue if you do so.
