### ISSUE TITLE
Requiem "Wandering Spirit" no longer an option to choose

### ISSUE THREAD

**Issue by Tankuu** [apace100/origins-fabric#94]
Just happened in the recent update I presume. Requiem hasn't had an update so I made the issue here assuming it was on this mod's side.

Not sure if this is intended in any way, and I am well aware that the "Opus Daemonium" banishment book makes you a Wandering Spirit, however having the choice might be a good idea to be disableable.

**Comment by apace100** [comment]
Hi, I am pretty sure this is fixed if you use Origins 0.5.0 or higher, thus I'm closing this issue (without having tested it specifically). If the issue still occurs, please let me know.
