### ISSUE TITLE
Aternos Compatibility/Incibibility

### ISSUE THREAD

**Issue by NoodleSins** [apace100/origins-fabric#95]
For some reason, my friend opened up an aternos server with fabric-api, and the origin mod. When I joined I got the option to chose my origin, while others didnt get a choice and was invicible. They couldnt be killed with /kill, couldnt even take damage from another player. 

We don't know why this is an issue, as it works in worlds for other people, just not in an ATERNOS server.
With other people a DYNIP doesnt even work. For my friends, it immediately gets a "Connection Lost" Screen before even getting in the server. I believe its an ATERNOS issue with the mod, but please HELP

**Comment by apace100** [comment]
Not getting an Origin choice and becoming invincible is caused by not having the Origins mod installed correctly on the client.

Getting "Connection Lost" when joining a server is caused by using a different Origins version on the server. Make sure they are the same.
